// Shared constants for the calendar package
export const COMPACT_EVENT_TIME_OPTIONS = {
  None: { key: '', label: 'None' },
  TitleLeft: { key: 'TitleLeft', label: 'Left of event title' },
  TitleRight: { key: 'TitleRight', label: 'Right of event title' },
  Description: { key: 'Description', label: 'Left of description' },
};

export const LAYOUT_OPTIONS = [
  {
    id: 1,
    name: 'Day view (Standard)',
    key: 'Day',
    category: 'day',
    subCategory: 'standard',
    isSelectedLayout: true,
    visible: true,
  },
  {
    id: 2,
    name: 'Day view (Vertical)',
    key: 'DayVertical',
    category: 'day',
    subCategory: 'vertical',
    isSelectedLayout: false,
    visible: true,
  },
  {
    id: 3,
    name: 'Day view (Horizontal)',
    key: 'DayHorizontal',
    category: 'day',
    subCategory: 'horizontal',
    isSelectedLayout: false,
    visible: true,
  },
  {
    id: 4,
    name: 'Week view (Standard)',
    key: 'Week',
    category: 'week',
    subCategory: 'standard',
    isSelectedLayout: false,
    visible: true,
  },
  {
    id: 5,
    name: 'Week view (Vertical)',
    key: 'WeekVertical',
    category: 'week',
    subCategory: 'vertical',
    isSelectedLayout: false,
    visible: true,
  },
  {
    id: 6,
    name: 'Week view (Horizontal)',
    key: 'WeekHorizontal',
    category: 'week',
    subCategory: 'horizontal',
    isSelectedLayout: false,
    visible: true,
  },
  {
    id: 7,
    name: 'Month view (Standard)',
    key: 'Month',
    category: 'month',
    subCategory: 'standard',
    isSelectedLayout: false,
    visible: true,
  },
  {
    id: 8,
    name: 'List view (Weekly)',
    key: 'ListWeek',
    category: 'list',
    subCategory: 'weekly',
    isSelectedLayout: false,
    visible: true,
  },
  {
    id: 9,
    name: 'List view (Monthly)',
    key: 'ListFull',
    category: 'list',
    subCategory: 'full',
    isSelectedLayout: false,
    visible: true,
  },
];
