import React, { useState } from 'react';
import PropTypes from 'prop-types';
import DataModelEditor from '../../src/views/layout-designer/editors/data-model-editor';

// types
const propTypes = {
  id: PropTypes.string,
  controlName: PropTypes.string,
  dataModelId: PropTypes.string,
  onChange: PropTypes.func,
  fieldListLoading: PropTypes.bool,
  fieldLoadingError: PropTypes.string,
};

function DataModelEditorWrapper({ id, controlName, dataModelId, onChange, fieldListLoading, fieldLoadingError }) {
  const [projection, setProjection] = useState({
    id: 'Contacts',
    fields: [
      {
        name: 'CompanyName',
        caption: 'Company name',
        type: 'Text',
        isVisible: true,
        isRequired: false,
        sourceModel: 'Entity',
        sourceField: 'CompanyName',
      },
      {
        name: 'AltEmail',
        caption: 'Alt email',
        type: 'Text',
        isVisible: true,
        isRequired: false,
        maxLength: null,
      },
      {
        name: 'Email',
        caption: 'Email',
        type: 'Text',
        isVisible: true,
        isRequired: false,
        maxLength: null,
      },
    ],
  });

  const [fieldList] = useState([
    {
      name: '12345',
      caption: '12345',
      type: 'Integer',
      isVisible: true,
      isRequired: false,
      sourceField: 'RecordID',
    },
    {
      name: 'AccountNumber',
      caption: 'Account number',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'AccountNumber',
    },
    {
      name: 'AltEmail',
      caption: 'Alt email',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceField: 'AltEmail',
    },
    {
      name: 'AltPhone',
      caption: 'Alt phone',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceField: 'AltPhone',
    },
    {
      name: 'AssignedTo',
      caption: 'Assigned to',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      isLinked: true,
      sourceModel: 'Entity',
      sourceField: 'UserName',
    },
    {
      name: 'AssignedToRecordID',
      caption: 'Assigned to record id',
      type: 'Integer',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'AssignedToRef_RecordID',
    },
    {
      name: 'Balance',
      caption: 'Balance',
      type: 'Money',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'Balance',
    },
    {
      name: 'BillAddressAddr1',
      caption: 'Bill address addr1',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressAddr1',
    },
    {
      name: 'BillAddressAddr2',
      caption: 'Bill address addr2',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressAddr2',
    },
    {
      name: 'BillAddressAddr3',
      caption: 'Bill address addr3',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressAddr3',
    },
    {
      name: 'BillAddressAddr4',
      caption: 'Bill address addr4',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressAddr4',
    },
    {
      name: 'BillAddressAddr5',
      caption: 'Bill address addr5',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressAddr5',
    },
    {
      name: 'BillAddressCity',
      caption: 'Bill address city',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressCity',
    },
    {
      name: 'BillAddressCountry',
      caption: 'Bill address country',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressCountry',
    },
    {
      name: 'BillAddressNote',
      caption: 'Bill address note',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressNote',
    },
    {
      name: 'BillAddressPostalCode',
      caption: 'Bill address postal code',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressPostalCode',
    },
    {
      name: 'BillAddressState',
      caption: 'Bill address state',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BillAddressState',
    },
    {
      name: 'BirthDate',
      caption: 'Birth date',
      type: 'DateTime',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'BirthDate',
    },
    {
      name: 'Campaign',
      caption: 'Campaign',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'Name',
    },
    {
      name: 'Class',
      caption: 'Class',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'FullName',
    },
    {
      name: 'CompanyName',
      caption: 'Company name',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'CompanyName',
    },
    {
      name: 'CPEPerYear',
      caption: 'Cpeper year',
      type: 'Decimal',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'CPEPerYear',
    },
    {
      name: 'Currency',
      caption: 'Currency',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'CurrencyCode',
    },
    {
      name: 'CustomerType',
      caption: 'Customer type',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'FullName',
    },
    {
      name: 'DirectDial',
      caption: 'Direct dial',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceField: 'DirectDial',
    },
    {
      name: 'Email',
      caption: 'Email',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceField: 'Email',
    },
    {
      name: 'EmployeeType',
      caption: 'Employee type',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'Name',
    },
    {
      name: 'Entity',
      caption: 'Entity',
      type: 'DropDown',
      isVisible: true,
      isRequired: false,
      sourceField: 'FullName',
    },
    {
      name: 'EntityCreatedDate',
      caption: 'Entity created date',
      type: 'DateTime',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'CreatedDate',
    },
    {
      name: 'EntityRecordID',
      caption: 'Entity record id',
      type: 'Integer',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'RecordID',
    },
    {
      name: 'EntityType',
      caption: 'Entity type',
      type: 'Text',
      isVisible: true,
      isRequired: false,
      sourceModel: 'Entity',
      sourceField: 'sEntityType',
    },
    {
      name: 'Entity_RecordID',
      caption: 'Entity_record id',
      type: 'Integer',
      isVisible: true,
      isRequired: false,
      sourceField: 'EntityRef',
    },
  ]);

  const [data] = useState({
    AccountNumber: '',
    AltEmail: '',
    AltPhone: '',
    AssignedTo: '',
    AssignedToRecordID: '',
    Balance: '0.0000',
    BillAddressAddr1: '',
    BillAddressAddr2: '',
    BillAddressAddr3: '',
    BillAddressAddr4: '',
    BillAddressAddr5: '',
    BillAddressCity: '',
    BillAddressCountry: '',
    BillAddressNote: '',
    BillAddressPostalCode: '',
    BillAddressState: '',
    BirthDate: '',
    Campaign: '',
    Class: '',
    CompanyName: '',
    CPEPerYear: '',
    Currency: '',
    CustomerType: '',
    DirectDial: '',
    Email: 'notifications@github.com',
    EmployeeType: '',
    Entity: 'mtran-method',
    Entity_RecordID: '323',
    EntityCreatedDate: '2021-04-12T08:56:39',
    EntityRecordID: '323',
    EntityType: 'Customer Lead',
    FaceBookUserName: '',
    Fax: '',
    FileB: '',
    FileBFileName: '',
    FirstName: 'mtran-method',
    FullName: 'mtran-method',
    Gender: '',
    ImageB: '',
    ImageBFileName: '',
    IMType: '',
    IMUserName: '',
    InstagramUserName: '',
    IsActive: 'True',
    IsActiveResource: 'False',
    IsContractor: 'False',
    IsCPE: 'False',
    IsEntityActive: 'True',
    IsGeneralBusiness: 'False',
    IsLeadStatusOnly: 'True',
    IsManufacturing: 'False',
    IsNonProfit: 'False',
    IsOptOutOfBilling: 'False',
    IsOptOutOfMarketing: 'False',
    IsProfessionalServices: 'False',
    IsResource: 'False',
    IsRetail: 'False',
    LastActivityCompletedDate: '',
    LastCompletedActivity: '',
    LastModifiedDate: '2021-04-12T08:56:39',
    LastName: '',
    LeadConvertedDate: '',
    LeadRating: '',
    LeadSource: '',
    LeadStatus: '',
    LinkedInPublicUserName: '',
    Mobile: '',
    Name: 'mtran-method',
    NextActivityDueDate: '',
    NextPendingActivity: '',
    Note: '',
    Pager: '',
    ParentFullName: '',
    Phone: '',
    PortalPassword: '',
    PortalUserName: '',
    PreferredPaymentMethod: '',
    PriceLevel: '',
    PrintAs: '',
    ProAdvisorLink: '',
    ProfileImage: 'M-2.mci{{w=48}}',
    ProfileImageFileName: 'M-2.mci',
    RecordID: '45',
    ResaleNumber: '',
    SalesRep: '',
    SalesRepRecordID: '323',
    SalesTaxCode: '',
    SalesTaxItem: '',
    ShipAddressAddr1: '',
    ShipAddressAddr2: '',
    ShipAddressAddr3: '',
    ShipAddressAddr4: '',
    ShipAddressAddr5: '',
    ShipAddressCity: '',
    ShipAddressCountry: '',
    ShipAddressNote: '',
    ShipAddressPostalCode: '',
    ShipAddressState: '',
    SkypeUserName: '',
    SpecialType: 'Contact',
    Sublevel: '0',
    TagList: '',
    TenantID: '1',
    Terms: '',
    Title: '',
    TotalBalance: '0.0000',
    TwitterUserName: '',
    VendorType: '',
    Website: '',
    YoutubeChannel: '',
  });

  const handleChange = (update) => {
    setProjection(update);
    onChange(update);
  };

  return (
    <div style={{ width: 380 }}>
      <DataModelEditor
        id={id}
        controlName={controlName}
        dataModelId={dataModelId}
        onChange={handleChange}
        fieldListLoading={fieldListLoading}
        fieldLoadingError={fieldLoadingError}
        projection={projection}
        fieldList={fieldList}
        data={data}
      />
    </div>
  );
}

DataModelEditorWrapper.propTypes = propTypes;
export default DataModelEditorWrapper;
