import { FieldTypeIds } from '@m-next/types';

export const tagsList = [
  {
    colour: '#A9D9BF',
    name: 'Hot lead ',
  },
  {
    colour: '#84F3FF',
    name: "Ala'a",
  },
  {
    colour: '#BACAD0',
    name: 'Sales Con',
  },
  {
    colour: '#B3E5FF',
    name: 'Duplicate',
  },
  {
    colour: '#FFCDAB',
    name: 'Unpaid',
  },
  {
    colour: '#FFCDAB',
    name: 'Super Long tag name with 2024',
  },
  {
    colour: '#FFCDAB',
    name: 'H_&_B',
  },
  {
    colour: '#FFCDAB',
    name: 'Elaine',
  },
  {
    colour: '#FFCDAB',
    name: "Al'n",
  },
  {
    colour: '#FFCDAB',
    name: 'For_you',
  },
];

export const tagsListSuggestions = ['Hot lead ', 'Duplicate', 'Unpaid'];

export const tagsListOpportunities = [
  {
    colour: '#A9D9BF',
    name: 'Hot lead ',
  },
  {
    colour: '#84F3FF',
    name: 'Cold lead',
  },
  {
    colour: '#BACAD0',
    name: 'MethodCon 2023',
  },

  {
    colour: '#FFCDAB',
    name: 'MethodCon 2024',
  },
  {
    colour: '#B3E5FF',
    name: 'Duplicate',
  },
  {
    colour: '#FFCDAB',
    name: 'Incorrect contact details',
  },
  {
    colour: '#FFCDAB',
    name: 'Super Long tag name with 2024',
  },
  {
    colour: '#FFCDAB',
    name: 'H_&_B',
  },
  {
    colour: '#FFCDAB',
    name: 'Elaine',
  },
  {
    colour: '#FFCDAB',
    name: "Al'n",
  },
  {
    colour: '#FFCDAB',
    name: 'For_you',
  },
];

export const data = [
  {
    RecordID: 1,
    Name: 'First',
    Value: 1,
    Money: 1,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Juvenile_Ragdoll.jpg/1024px-Juvenile_Ragdoll.jpg',
    Company: { value: 1, label: 'Mnemonic' },
    Image: 'https://cdn.shopify.com/s/files/1/0272/4770/6214/files/Blog_-_Newborn_Kitten_Care_Week_by_Week_600x600.jpg',
  },
  {
    RecordID: 2,
    Name: 'Second',
    Value: 2,
    Money: 2,
    Date: '',
    ProfileImage: 'S-3.mci{{w=24}}',
    Company: { value: 1, label: 'Mnemonic' },
    Phone: '416 555 5555',
    TagList: 'Hot lead,Sales Con',
  },
  {
    RecordID: 3,
    Name: 'Third',
    Value: 3.5,
    Money: 3.5,
    Date: null,
    ProfileImage: 'T-3.mci{{w=24}}',
    Company: { value: 2, label: 'Weyland-Yutani' },
    Phone: '416 555 5555',
    TagList: 'Hot lead,Sales Con,Unpaid',
    LongText:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    RecordID: 4,
    Name: 'Fourth',
    Value: 4,
    Money: 4,
    Date: '',
    ProfileImage: 'F-3.mci{{w=24}}',
    Company: { value: 2, label: 'Weyland-Yutani' },
    TagList: 'Hot lead,Sales Con,Unpaid,Super Long tag name with 2024,Duplicate',
  },
  {
    RecordID: 5,
    Name: 'Fifth',
    Value: 5,
    Money: 5,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage: 'F-3.mci{{w=24}}',
    Company: { value: 2, label: 'Weyland-Yutani' },
    TagList: 'Cold lead',
  },
  {
    RecordID: 6,
    Name: 'Sixth',
    Value: 6.5,
    Money: 6.5,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage: 'S-3.mci{{w=24}}',
    Company: null,
    Phone: '416 555 5555',
    TagList: 'Cold lead,Sales Con',
  },
  {
    RecordID: 7,
    Name: 'Seventh',
    Value: 7,
    Money: 7,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage: 'S-3.mci{{w=24}}',
    Company: { value: 1, label: 'Mnemonic' },
    TagList: 'Cold lead,Sales Con',
  },
  {
    RecordID: 8,
    Name: 'Eigth',
    Value: 8,
    Money: 8,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage: 'E-3.mci{{w=24}}',
    Company: null,
    TagList: 'Cold lead,Sales Con',
  },
  {
    RecordID: 9,
    Name: 'Nineth',
    Value: 9.5,
    Money: 9.5,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage: 'N-3.mci{{w=24}}',
    Company: null,
    TagList: 'Cold lead',
  },
  {
    RecordID: 10,
    Name: 'Tenth',
    Value: 10,
    Money: 10,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage: 'T-3.mci{{w=24}}',
    Company: { value: 3, label: 'Azteca' },
    TagList: 'Cold lead',
  },
  {
    RecordID: 11,
    Name: 'Eleventh',
    Value: 11,
    Money: 11,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage: 'E-3.mci{{w=24}}',
    Company: { value: 1, label: 'Mnemonic' },
    TagList: 'Cold lead',
  },
  {
    RecordID: 12,
    Name: 'Twelfth',
    Value: 12.5,
    Money: 12.5,
    Date: '2022-08-02T19:04:33.204Z',
    DateTime: '2022-08-02T19:04:33.204Z',
    Time: '2022-08-02T19:04:33.204Z',
    ProfileImage: 'T-3.mci{{w=24}}',
    TagList: 'Cold lead',
  },
];

export const dataOpportunity = [
  {
    RecordID: 1,
    Name: 'Lead - SteelForge Industries',
    Value: 205000,
    ActualValue: 0,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    ModifiedOn: '2024-04-02T19:04:33.204Z',
    Stage: { value: 1, label: 'New' },
    TagList: 'Hot lead,MethodCon 2024',
  },
  {
    RecordID: 2,
    Name: 'Lead - TechPlast Solutions',
    Value: 3600,
    ActualValue: 3000,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    Stage: { value: 3, label: 'Awaiting Approval' },
    TagList: 'Hot lead,MethodCon 2024',
  },
  {
    RecordID: 3,
    Name: 'Lead - PrecisionMetal Works',
    Value: 132500,
    ActualValue: 0,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    Stage: { value: 1, label: 'New' },
    TagList: 'Hot lead,MethodCon 2024',
  },
  {
    RecordID: 4,
    Name: 'Lead - GreenEco Manufacturing',
    Value: 500,
    ActualValue: 0,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    Stage: { value: 1, label: 'New' },
    TagList: 'Hot lead,MethodCon 2024',
  },
  {
    RecordID: 5,
    Name: 'Lead - InnovateMach Engineering',
    Value: 500000,
    ActualValue: 0,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    Stage: { value: 1, label: 'New' },
    TagList: 'Hot lead,MethodCon 2024',
  },
  {
    RecordID: 6,
    Name: 'Lead - BioPolymer Innovations',
    Value: 18000,
    ActualValue: 0,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    Stage: { value: 1, label: 'New' },
    TagList: 'MethodCon 2024',
  },
  {
    RecordID: 7,
    Name: 'Lead - QuantumTech Manufacturing',
    Value: 95000,
    ActualValue: 0,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    Stage: { value: 2, label: 'Negotiation' },
    TagList: 'Hot lead,MethodCon 2023',
  },
  {
    RecordID: 8,
    Name: 'Lead - AeroTech Dynamics',
    Value: 32000,
    ActualValue: 0,
    CreatedDate: '2024-04-11T19:04:33.204Z',
    Stage: { value: 1, label: 'New' },
    TagList: 'Hot lead',
  },
  {
    RecordID: 9,
    Name: 'Lead - BioTech Fabrications',
    Value: 45000,
    ActualValue: 0,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    Stage: { value: 1, label: 'New' },
  },
  {
    RecordID: 10,
    Name: 'Lead - SustainableStructures Corp.',
    Value: 86000,
    ActualValue: 0,
    CreatedDate: '2024-04-01T19:04:33.204Z',
    Stage: { value: 4, label: 'Lost' },
    TagList: 'MethodCon 2024',
  },
];

export const columns = [
  {
    primary: true,
    name: 'RecordID',
    editable: false,
    fieldType: FieldTypeIds.Integer,
    visible: false,
    columnAlign: 'left',
    width: 'sm',
  },
  {
    primary: false,
    name: 'ProfileImage',
    editable: true,
    fieldType: FieldTypeIds.Picture,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
  },
  {
    primary: false,
    name: 'Name',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'left',
    width: 'sm',
  },

  {
    primary: false,
    name: 'Company',
    caption: 'Really Long Company Name To Display',
    editable: true,
    fieldType: FieldTypeIds.DropDown,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    accessorProp: 'label',
  },
  {
    primary: false,
    name: 'Phone',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'left',
    width: 'md',
  },
  {
    primary: false,
    name: 'Value',
    editable: true,
    fieldType: FieldTypeIds.Decimal,
    visible: true,
    columnAlign: 'right',
    width: 'sm',
    hasColumnTotal: true,
  },
  {
    primary: false,
    name: 'Money',
    editable: true,
    fieldType: FieldTypeIds.Money,
    visible: true,
    columnAlign: 'right',
    width: 'sm',
  },
  {
    primary: false,
    name: 'DateTime',
    caption: 'DateTime',
    editable: true,
    fieldType: FieldTypeIds.DateTime,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
  },
  {
    primary: false,
    name: 'Date',
    caption: 'Date',
    editable: true,
    fieldType: FieldTypeIds.DateTime,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    format: {
      dateType: 'Month and Year',
    },
  },
  {
    primary: false,
    name: 'Time',
    caption: 'Time',
    editable: true,
    fieldType: FieldTypeIds.DateTime,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    format: {
      dateType: 'Time',
    },
  },
  {
    primary: false,
    name: 'Image',
    editable: true,
    fieldType: FieldTypeIds.Picture,
    visible: true,
    columnAlign: 'left',
    width: 'sm',
  },
  {
    primary: false,
    name: 'LongText',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'center',
    width: 'lg',
  },
  {
    primary: false,
    name: 'TagList',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
  },
  {
    primary: false,
    name: 'Button',
    editable: true,
    fieldType: FieldTypeIds.Button,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    buttonLabel: 'Button',
  },
  {
    primary: false,
    name: 'IsPaid',
    editable: true,
    fieldType: FieldTypeIds.YesNo,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    caption: 'Is paid',
  },
];

export const autoSizeColumns = [
  {
    primary: true,
    name: 'RecordID',
    editable: false,
    fieldType: FieldTypeIds.Integer,
    visible: false,
    columnAlign: 'left',
    width: 'auto',
  },
  {
    primary: false,
    name: 'ProfileImage',
    editable: true,
    fieldType: FieldTypeIds.Picture,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
  },
  {
    primary: false,
    name: 'Name',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'left',
    width: 'auto',
  },

  {
    primary: false,
    name: 'Company',
    caption: 'Really Long Company Name To Display',
    editable: true,
    fieldType: FieldTypeIds.DropDown,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
    accessorProp: 'label',
  },
  {
    primary: false,
    name: 'Phone',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'left',
    width: 'fixed',
    widthFixed: 120,
  },
  {
    primary: false,
    name: 'Value',
    editable: true,
    fieldType: FieldTypeIds.Decimal,
    visible: true,
    columnAlign: 'right',
    width: 'auto',
    hasColumnTotal: true,
  },
  {
    primary: false,
    name: 'Money',
    editable: true,
    fieldType: FieldTypeIds.Money,
    visible: true,
    columnAlign: 'right',
    width: 'auto',
  },
  {
    primary: false,
    name: 'DateTime',
    caption: 'DateTime',
    editable: true,
    fieldType: FieldTypeIds.DateTime,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
  },
  {
    primary: false,
    name: 'Date',
    caption: 'Date',
    editable: true,
    fieldType: FieldTypeIds.DateTime,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
    format: {
      dateType: 'Month and Year',
    },
  },
  {
    primary: false,
    name: 'Time',
    caption: 'Time',
    editable: true,
    fieldType: FieldTypeIds.DateTime,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
    format: {
      dateType: 'Time',
    },
  },
  {
    primary: false,
    name: 'Image',
    editable: true,
    fieldType: FieldTypeIds.Picture,
    visible: true,
    columnAlign: 'left',
    width: 'auto',
  },
  {
    primary: false,
    name: 'LongText',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
    widthAutoSize: 'lg',
  },
  {
    primary: false,
    name: 'TagList',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
  },
  {
    primary: false,
    name: 'Button',
    editable: true,
    fieldType: FieldTypeIds.Button,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
    buttonLabel: 'Button',
  },
  {
    primary: false,
    name: 'IsPaid',
    editable: true,
    fieldType: FieldTypeIds.YesNo,
    visible: true,
    columnAlign: 'center',
    width: 'auto',
    caption: 'Is paid',
  },
];

export const columnsOpportunities = [
  {
    primary: true,
    name: 'RecordID',
    caption: 'RecordID',
    editable: false,
    fieldType: FieldTypeIds.Integer,
    visible: false,
    columnAlign: 'left',
    width: 'sm',
    hideable: false,
  },
  {
    primary: false,
    name: 'Name',
    caption: 'Name',
    editable: true,
    fieldType: FieldTypeIds.Text,
    visible: true,
    columnAlign: 'left',
    width: 'sm',
  },
  {
    primary: false,
    name: 'Value',
    caption: 'Value',
    editable: true,
    fieldType: FieldTypeIds.Money,
    visible: true,
    columnAlign: 'right',
    width: 'sm',
  },
  {
    primary: false,
    name: 'ActualValue',
    caption: 'ActualValue',
    editable: true,
    fieldType: FieldTypeIds.Money,
    visible: true,
    columnAlign: 'right',
    width: 'sm',
  },
  {
    primary: false,
    name: 'CreatedDate',
    caption: 'Created date',
    editable: true,
    fieldType: FieldTypeIds.DateTime,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    format: {
      dateType: 'Short Date',
    },
  },
  {
    primary: false,
    name: 'ModifiedOn',
    caption: 'Modified on',
    editable: true,
    fieldType: FieldTypeIds.DateTime,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    format: {
      dateType: 'Short Date and Time',
    },
  },
  {
    primary: false,
    name: 'Stage',
    caption: 'Stage',
    editable: true,
    fieldType: FieldTypeIds.DropDown,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    accessorProp: 'label',
  },
  {
    primary: false,
    name: 'TagList',
    caption: 'TagList',
    editable: true,
    fieldType: FieldTypeIds.Tags,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
  },
];

export const columnsSmall = [
  {
    primary: true,
    name: 'RecordID',
    editable: false,
    fieldType: FieldTypeIds.Integer,
    visible: false,
    columnAlign: 'left',
    width: 'sm',
  },
  {
    primary: false,
    name: 'ProfileImage',
    editable: true,
    fieldType: FieldTypeIds.Picture,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
  },
  {
    primary: false,
    name: 'IsPaid',
    editable: true,
    fieldType: FieldTypeIds.YesNo,
    visible: true,
    columnAlign: 'center',
    width: 'sm',
    caption: 'Is paid',
  },
];

export const legacyColumn = [
  {
    controlId: '4ebce6a9-8631-e73c-3738-e4a229b367a3',
    header: 'Customer',
    field: 'Customer',
    fieldType: 8,
    columnType: 0,
    onChangeEvent: null,
    defaultValue: {
      ValueType: 9,
      Value: null,
      Property: null,
      ChildProperty: null,
      ValidationMessage: null,
      FontStyles: null,
    },
    readOnly: false,
    canDelete: false,
    isLocked: false,
    cardColumnFields: null,
    showOnMobile: false,
    visibleOnMobile: true,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: null,
      rounding: null,
      separator: null,
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: null,
      headerAlignment: null,
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: [
      {
        rule: 0,
        value: null,
        canDelete: false,
      },
    ],
    control: {
      onLoseFocus: null,
      Type: 'DRP',
      selectedValue: '-1',
      selectedText: null,
      FieldType: 8,
      customRowText: '',
      dataSet: null,
      iconAlign: null,
      displayTag: null,
      infiniteScroll: 0,
      isClearable: false,
      isFilterable: true,
      isFixedLayout: false,
      isInPopup: false,
      isUsingNoWrap: false,
      loadRemoteData: false,
      model: {
        activeRow: -1,
        processServerSide: false,
        dataSource: [],
        viewName: 'Customer',
        viewFilter: {
          filterId: '3ac53101-690e-2543-8403-40293ac38786',
          filterName: 'DrpFilter',
          viewName: 'Customer',
          versionId: '00000000-0000-0000-0000-000000000000',
          searchString: null,
          isDefault: true,
          isHidden: false,
          state: 1,
          expression: [],
          sorting: [],
          hidden: [],
          visibleColumns: null,
        },
        distinct: false,
        columns: [
          {
            name: 'RecordID',
            caption: 'Record ID',
            isKey: true,
            columnType: 0,
            width: 0,
            format: {
              display: 0,
              visible: false,
              width: {
                value: null,
                type: 0,
                mvalue: null,
                mtype: 0,
              },
              icon: {
                name: null,
                color: null,
              },
              visiblemobile: false,
              alignment: '',
              formatType: '',
              formatRounding: null,
              formatSeparator: null,
              hidecaption: false,
            },
            cardColumnFields: null,
            hasSubtotal: false,
            subtotal: 0,
            ignore: false,
            isLinked: false,
            tableNameRef: null,
            isRequired: false,
            isUnique: false,
            size: 0,
            id: 0,
            linkedFieldCaption: null,
            linkedJoinFromTable: null,
            linkedJoinFromPrimary: null,
            linkedViaField: null,
            compareName: null,
            displayValueFromTableName: null,
            displayValueFromFieldName: null,
            displayValueFromViewFriendlyName: null,
            maxSize: 0,
            isComplexField: false,
            parentFieldName: null,
            parentFieldType: null,
            elementType: null,
            elementSeq: null,
            elements: null,
            fieldType: 2,
            onClick: null,
            expression: null,
            aggregate: null,
            dateGroupBy: null,
            validationRules: null,
          },
          {
            name: 'FullName',
            caption: 'FullName',
            isKey: false,
            columnType: 0,
            width: 0,
            format: {
              display: 0,
              visible: true,
              width: {
                value: null,
                type: 0,
                mvalue: null,
                mtype: 0,
              },
              icon: {
                name: null,
                color: null,
              },
              visiblemobile: true,
              alignment: '',
              formatType: '',
              formatRounding: '',
              formatSeparator: '',
              hidecaption: false,
            },
            cardColumnFields: null,
            hasSubtotal: false,
            subtotal: 0,
            ignore: false,
            isLinked: false,
            tableNameRef: null,
            isRequired: false,
            isUnique: false,
            size: 0,
            id: 0,
            linkedFieldCaption: null,
            linkedJoinFromTable: null,
            linkedJoinFromPrimary: null,
            linkedViaField: null,
            compareName: null,
            displayValueFromTableName: null,
            displayValueFromFieldName: null,
            displayValueFromViewFriendlyName: null,
            maxSize: 0,
            isComplexField: false,
            parentFieldName: null,
            parentFieldType: null,
            elementType: null,
            elementSeq: null,
            elements: null,
            fieldType: 0,
            onClick: null,
            expression: null,
            aggregate: null,
            dateGroupBy: null,
            validationRules: null,
          },
        ],
        sorting: null,
        paging: {
          pageNumber: 1,
          pageSize: 50,
          totalRows: 0,
        },
        selectAll: false,
        selectedRecords: [],
      },
      onCustomRowClick: null,
      placeholder: '',
      showCurrency: false,
      TypeOverride: '',
      isLinked: false,
      filterDef: null,
      selectedRecord: null,
      id: '4ebce6a9-8631-e73c-3738-e4a229b367a3',
      name: 'Customer',
      isBound: false,
      IsComplexType: false,
      value: '-1',
      caption: '',
      classes: '',
      hideCaption: false,
      isOutputOnly: false,
      regularCaption: true,
      width: '',
      widthType: 'full',
      visible: true,
      disabled: false,
      defaultValue: '',
      onBlur: null,
      onChange: null,
      onClick: null,
      onFocus: null,
      validationRules: [],
      validationError: null,
    },
    expression: null,
    hasColumnTotal: false,
    displayField: 'Customer',
  },
  {
    controlId: '1d92e066-b9ea-33c6-b6f7-3707e0a658b4',
    header: 'RecordID',
    field: 'RecordID',
    fieldType: 2,
    columnType: 0,
    onChangeEvent: null,
    defaultValue: {
      ValueType: 9,
      Value: '',
      Property: '',
      ChildProperty: null,
      ValidationMessage: '',
      FontStyles: null,
    },
    readOnly: true,
    canDelete: false,
    isLocked: true,
    cardColumnFields: null,
    showOnMobile: false,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: null,
      rounding: null,
      separator: null,
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: null,
      headerAlignment: null,
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: [
      {
        rule: 0,
        value: null,
        canDelete: false,
      },
    ],
    control: null,
    expression: null,
    hasColumnTotal: false,
    displayField: 'RecordID',
  },
  {
    controlId: '60d13c03-cc2e-8b04-d07d-5757ba47271f',
    header: 'TxnDate',
    field: 'TxnDate',
    fieldType: 3,
    columnType: 0,
    onChangeEvent: null,
    defaultValue: {
      ValueType: 9,
      Value: null,
      Property: null,
      ChildProperty: null,
      ValidationMessage: null,
      FontStyles: null,
    },
    readOnly: false,
    canDelete: false,
    isLocked: false,
    cardColumnFields: null,
    showOnMobile: false,
    visibleOnMobile: true,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: 'Short Date and Time',
      rounding: null,
      separator: null,
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: 'Date',
      headerAlignment: null,
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: [
      {
        rule: 0,
        value: null,
        canDelete: false,
      },
    ],
    control: null,
    expression: null,
    hasColumnTotal: false,
    displayField: 'TxnDate',
  },
  {
    controlId: '09f6b5d0-fd1d-e0af-5f87-7cacaf41bbcf',
    header: 'DueDate',
    field: 'DueDate',
    fieldType: 3,
    columnType: 0,
    onChangeEvent: null,
    defaultValue: {
      ValueType: 9,
      Value: null,
      Property: null,
      ChildProperty: null,
      ValidationMessage: null,
      FontStyles: null,
    },
    readOnly: false,
    canDelete: true,
    isLocked: false,
    cardColumnFields: null,
    showOnMobile: false,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: 'Month and Year',
      rounding: '0',
      separator: null,
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: 'Date',
      headerAlignment: null,
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: [
      {
        rule: 2,
        value: null,
        canDelete: false,
      },
    ],
    control: null,
    expression: null,
    hasColumnTotal: false,
    displayField: 'DueDate',
  },
  {
    controlId: '24bdc49b-9a96-403f-2f1e-4687065c5e4c',
    header: 'Amount',
    field: 'Amount',
    fieldType: 4,
    columnType: 0,
    onChangeEvent: null,
    defaultValue: {
      ValueType: 9,
      Value: null,
      Property: null,
      ChildProperty: null,
      ValidationMessage: null,
      FontStyles: null,
    },
    readOnly: false,
    canDelete: true,
    isLocked: false,
    cardColumnFields: null,
    showOnMobile: false,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: 'Number',
      rounding: '2',
      separator: 'Yes',
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: null,
      headerAlignment: null,
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: [],
    control: null,
    expression: null,
    hasColumnTotal: false,
    displayField: 'Amount',
  },
  {
    controlId: '24e2a1f4-4653-ca7b-75d9-5f8380624f66',
    header: 'TagList',
    field: 'TagList',
    fieldType: 0,
    columnType: 0,
    onChangeEvent: null,
    defaultValue: {
      ValueType: 9,
      Value: null,
      Property: null,
      ChildProperty: null,
      ValidationMessage: null,
      FontStyles: null,
    },
    readOnly: false,
    canDelete: true,
    isLocked: false,
    cardColumnFields: null,
    showOnMobile: false,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: null,
      rounding: null,
      separator: null,
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: null,
      headerAlignment: null,
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: [
      {
        rule: 2,
        value: 4000,
        canDelete: false,
      },
      {
        rule: 6,
        value: true,
        canDelete: true,
      },
    ],
    control: null,
    expression: null,
    hasColumnTotal: false,
    displayField: 'TagList',
  },
  {
    controlId: 'ade0c823-e7fe-f011-6308-9965f29c1eb9',
    header: 'CardColumn1',
    field: 'CardColumn1',
    fieldType: 11,
    columnType: 4,
    onChangeEvent: null,
    defaultValue: {
      ValueType: 9,
      Value: '',
      Property: '',
      ChildProperty: null,
      ValidationMessage: '',
      FontStyles: null,
    },
    readOnly: true,
    canDelete: true,
    isLocked: true,
    cardColumnFields: [
      {
        format: {
          width: null,
          widthFixed: null,
          alignment: null,
          type: 'DropDown',
          rounding: '2',
          separator: 'Yes',
          decimalPoint: null,
          thousands: null,
          money: null,
          dateType: null,
          fontSize: null,
          textColor: null,
          backgroundColor: null,
          visible: true,
        },
        fldTypeId: 8,
        label: 'Customer',
        table: 'Customer',
        value: 'Customer',
      },
      {
        format: {
          width: null,
          widthFixed: null,
          alignment: null,
          type: 'DropDown',
          rounding: '2',
          separator: 'Yes',
          decimalPoint: null,
          thousands: null,
          money: null,
          dateType: null,
          fontSize: null,
          textColor: null,
          backgroundColor: null,
          visible: true,
        },
        fldTypeId: 8,
        label: 'AssignedTo',
        table: 'Users',
        value: 'AssignedTo',
      },
      {
        format: {
          width: null,
          widthFixed: null,
          alignment: null,
          type: 'YesNo',
          rounding: '2',
          separator: 'Yes',
          decimalPoint: null,
          thousands: null,
          money: null,
          dateType: null,
          fontSize: null,
          textColor: null,
          backgroundColor: null,
          visible: true,
        },
        fldTypeId: 5,
        label: 'IsPaid',
        table: 'Invoice',
        value: 'IsPaid',
      },
      {
        format: {
          width: null,
          widthFixed: null,
          alignment: null,
          type: 'Money',
          rounding: '2',
          separator: 'Yes',
          decimalPoint: null,
          thousands: null,
          money: null,
          dateType: null,
          fontSize: null,
          textColor: null,
          backgroundColor: null,
          visible: true,
        },
        fldTypeId: 4,
        label: 'Amount',
        table: 'Invoice',
        value: 'Amount',
      },
      {
        format: {
          width: null,
          widthFixed: null,
          alignment: null,
          type: 'DateTime',
          rounding: null,
          separator: null,
          decimalPoint: null,
          thousands: null,
          money: null,
          dateType: 'Short Date and Time',
          fontSize: null,
          textColor: null,
          backgroundColor: null,
          visible: true,
        },
        fldTypeId: 3,
        label: 'TimeCreated',
        table: 'Invoice',
        value: 'TimeCreated',
      },
      {
        format: {
          width: null,
          widthFixed: null,
          alignment: null,
          type: 'Text',
          rounding: null,
          separator: null,
          decimalPoint: null,
          thousands: null,
          money: null,
          dateType: null,
          fontSize: null,
          textColor: null,
          backgroundColor: null,
          visible: true,
        },
        fldTypeId: 0,
        label: 'TagList',
        table: 'Invoice',
        value: 'TagList',
      },
      {
        format: null,
        fldTypeId: 0,
        label: null,
        table: null,
        value: null,
      },
    ],
    showOnMobile: true,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: 'avatar-2-cols',
      rounding: null,
      separator: null,
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: null,
      headerAlignment: 'left',
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: null,
    control: {
      Type: 'CRD',
      Class: null,
      defaultValue: 'CardColumn1',
      id: 'ade0c823-e7fe-f011-6308-9965f29c1eb9',
      name: 'CardColumn1',
      TypeOverride: 'CRD',
      isBound: false,
      IsComplexType: false,
      FieldType: 0,
      value: 'CardColumn1',
      caption: 'CardColumn1',
      classes: '',
      hideCaption: false,
      isOutputOnly: false,
      regularCaption: false,
      width: null,
      widthType: null,
      visible: false,
      disabled: false,
      onBlur: null,
      onChange: null,
      onClick: null,
      onFocus: null,
      validationRules: null,
      validationError: null,
    },
    expression: null,
    hasColumnTotal: false,
    displayField: 'CardColumn1',
  },
  {
    controlId: '978b6fae-e085-eea9-1492-8a52a525ac65',
    header: 'Button1',
    field: 'Button1',
    fieldType: 10,
    columnType: 3,
    onChangeEvent: 'd173a186-cfec-e945-c86b-2d7607183bd5',
    defaultValue: {
      ValueType: 9,
      Value: '',
      Property: '',
      ChildProperty: null,
      ValidationMessage: '',
      FontStyles: null,
    },
    readOnly: true,
    canDelete: true,
    isLocked: false,
    cardColumnFields: null,
    showOnMobile: false,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: null,
      rounding: null,
      separator: null,
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: null,
      headerAlignment: null,
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: [],
    control: {
      Type: 'BTN',
      Class: 'mi-button',
      icon: '',
      iconAlign: 'Left',
      defaultValue: 'Button1',
      id: '978b6fae-e085-eea9-1492-8a52a525ac65',
      name: 'BTN-Button1',
      TypeOverride: 'BTN',
      isBound: false,
      IsComplexType: false,
      FieldType: 0,
      value: 'Button1',
      caption: 'Button1',
      classes: '',
      hideCaption: false,
      isOutputOnly: false,
      regularCaption: false,
      width: '',
      widthType: 'auto',
      visible: true,
      disabled: false,
      onBlur: null,
      onChange: null,
      onClick: null,
      onFocus: null,
      validationRules: null,
      validationError: null,
    },
    expression: null,
    hasColumnTotal: false,
    displayField: 'Button1',
  },
  {
    controlId: '17413423-22f1-cc4f-4a06-2d9164f2bf04',
    header: 'IsPaid',
    field: 'IsPaid',
    fieldType: 5,
    columnType: 0,
    onChangeEvent: null,
    defaultValue: {
      ValueType: 9,
      Value: null,
      Property: null,
      ChildProperty: null,
      ValidationMessage: '',
      FontStyles: null,
    },
    readOnly: false,
    canDelete: true,
    isLocked: false,
    cardColumnFields: null,
    showOnMobile: false,
    format: {
      width: 'md',
      widthFixed: null,
      alignment: 'left',
      type: null,
      rounding: null,
      separator: null,
      decimalPoint: null,
      thousands: null,
      money: null,
      dateType: null,
      headerAlignment: null,
      fontSize: null,
      textColor: null,
      backgroundColor: null,
      visible: true,
      disabled: false,
    },
    validationRules: [
      {
        rule: 2,
        value: null,
        canDelete: false,
      },
    ],
    control: null,
    expression: null,
    hasColumnTotal: false,
    displayField: 'IsPaid',
  },
];

export const legacyData = [
  {
    cells: [
      {
        text: 'Alex',
        name: 'Customer',
        value: 276,
        validationError: null,
      },
      {
        text: '55',
        name: 'RecordID',
        value: 55,
        validationError: null,
      },
      {
        text: '2016-03-10T17:00:00',
        name: 'TxnDate',
        value: '2016-03-10T17:00:00',
        validationError: null,
      },
      {
        text: '2016-03-10T17:00:00',
        name: 'DueDate',
        value: '2016-03-10T17:00:00',
        validationError: null,
      },
      {
        text: '167.2500',
        name: 'Amount',
        value: 167.25,
        validationError: null,
      },
      {
        text: 'BBB',
        name: 'TagList',
        value: 'BBB',
        validationError: null,
      },
      {
        text: 'Alex||Alexander Ballard||False||167.2500||||BBB',
        name: 'CardColumn1',
        value: 'Alex||Alexander Ballard||False||167.2500||||BBB',
        validationError: null,
      },
      {
        text: 'Button1',
        name: 'Button1',
        value: 'Button1',
        validationError: null,
      },
      {
        text: 'False',
        name: 'IsPaid',
        value: false,
        validationError: null,
      },
    ],
    selected: false,
    status: 0,
  },
  {
    cells: [
      {
        text: 'Alex',
        name: 'Customer',
        value: 276,
        validationError: null,
      },
      {
        text: '56',
        name: 'RecordID',
        value: 56,
        validationError: null,
      },
      {
        text: '2016-04-14T12:00:00',
        name: 'TxnDate',
        value: '2016-04-14T12:00:00',
        validationError: null,
      },
      {
        text: '2016-04-14T12:00:00',
        name: 'DueDate',
        value: '2016-04-14T12:00:00',
        validationError: null,
      },
      {
        text: '',
        name: 'Amount',
        value: '',
        validationError: null,
      },
      {
        text: 'dc6',
        name: 'TagList',
        value: 'dc6',
        validationError: null,
      },
      {
        text: 'Alex||Alexander Ballard||False||||||dc6',
        name: 'CardColumn1',
        value: 'Alex||Alexander Ballard||False||||||dc6',
        validationError: null,
      },
      {
        text: 'Button1',
        name: 'Button1',
        value: 'Button1',
        validationError: null,
      },
      {
        text: 'False',
        name: 'IsPaid',
        value: false,
        validationError: null,
      },
    ],
    selected: false,
    status: 0,
  },
  {
    cells: [
      {
        text: 'PROD',
        name: 'Customer',
        value: 281,
        validationError: null,
      },
      {
        text: '57',
        name: 'RecordID',
        value: 57,
        validationError: null,
      },
      {
        text: '2016-04-27T12:00:00',
        name: 'TxnDate',
        value: '2016-04-27T12:00:00',
        validationError: null,
      },
      {
        text: '2016-04-27T12:00:00',
        name: 'DueDate',
        value: '2016-04-27T12:00:00',
        validationError: null,
      },
      {
        text: '',
        name: 'Amount',
        value: '',
        validationError: null,
      },
      {
        text: 'dc6',
        name: 'TagList',
        value: 'dc6',
        validationError: null,
      },
      {
        text: 'PROD||mila||False||||||dc6',
        name: 'CardColumn1',
        value: 'PROD||mila||False||||||dc6',
        validationError: null,
      },
      {
        text: 'Button1',
        name: 'Button1',
        value: 'Button1',
        validationError: null,
      },
      {
        text: 'False',
        name: 'IsPaid',
        value: false,
        validationError: null,
      },
    ],
    selected: false,
    status: 0,
  },
  {
    cells: [
      {
        text: 'PROD6',
        name: 'Customer',
        value: 283,
        validationError: null,
      },
      {
        text: '58',
        name: 'RecordID',
        value: 58,
        validationError: null,
      },
      {
        text: '2016-04-27T12:00:00',
        name: 'TxnDate',
        value: '2016-04-27T12:00:00',
        validationError: null,
      },
      {
        text: '2016-04-27T12:00:00',
        name: 'DueDate',
        value: '2016-04-27T12:00:00',
        validationError: null,
      },
      {
        text: '8.0000',
        name: 'Amount',
        value: 8,
        validationError: null,
      },
      {
        text: '',
        name: 'TagList',
        value: '',
        validationError: null,
      },
      {
        text: 'PROD6||mila||False||8.0000||||',
        name: 'CardColumn1',
        value: 'PROD6||mila||False||8.0000||||',
        validationError: null,
      },
      {
        text: 'Button1',
        name: 'Button1',
        value: 'Button1',
        validationError: null,
      },
      {
        text: 'False',
        name: 'IsPaid',
        value: false,
        validationError: null,
      },
    ],
    selected: false,
    status: 0,
  },
  {
    cells: [
      {
        text: 'Alex',
        name: 'Customer',
        value: 276,
        validationError: null,
      },
      {
        text: '59',
        name: 'RecordID',
        value: 59,
        validationError: null,
      },
      {
        text: '2016-08-17T12:00:00',
        name: 'TxnDate',
        value: '2016-08-17T12:00:00',
        validationError: null,
      },
      {
        text: '2016-08-17T12:00:00',
        name: 'DueDate',
        value: '2016-08-17T12:00:00',
        validationError: null,
      },
      {
        text: '213.6000',
        name: 'Amount',
        value: 213.6,
        validationError: null,
      },
      {
        text: '',
        name: 'TagList',
        value: '',
        validationError: null,
      },
      {
        text: 'Alex||Alexander Ballard||False||213.6000||||',
        name: 'CardColumn1',
        value: 'Alex||Alexander Ballard||False||213.6000||||',
        validationError: null,
      },
      {
        text: 'Button1',
        name: 'Button1',
        value: 'Button1',
        validationError: null,
      },
      {
        text: 'False',
        name: 'IsPaid',
        value: false,
        validationError: null,
      },
    ],
    selected: false,
    status: 0,
  },
];
