export const DOMPurifyOptions = {
  FORBID_TAGS: ['script', 'noscript', 'style', 'iframe', 'embed', 'object', 'applet', 'link', 'base'],
  FORBID_ATTR: [
    'onload',
    'onerror',
    'onclick',
    'onmouseover',
    'onfocus',
    'onblur',
    'onkeydown',
    'onkeyup',
    'onkeypress',
    'onmousemove',
    'onmouseenter',
    'onmouseleave',
    'onsubmit',
    'onreset',
    'style',
    'srcdoc',
    'xlink:href',
    'formaction',
  ],
};

export const EnhancedDOMPurifyOptions = {
  FORBID_TAGS: [
    ...DOMPurifyOptions.FORBID_TAGS,
    'a',
    'area',
    'audio',
    'basefont',
    'bgsound',
    'button',
    'canvas',
    'code',
    'form',
    'frame',
    'frameset',
    'img',
    'input',
    'math',
    'meta',
    'param',
    'plaintext',
    'select',
    'source',
    'svg',
    'textarea',
    'track',
    'video',
    'xmp',
  ],
  FORBID_ATTR: DOMPurifyOptions.FORBID_ATTR,
};

export const EnhancedDOMPurifyOptionsLabel = {
  FORBID_TAGS: ['script', 'noscript', 'style', 'iframe', 'embed', 'object', 'applet', 'link', 'base'],
  FORBID_ATTR: [
    'onload',
    'onerror',
    'onclick',
    'onmouseover',
    'onfocus',
    'onblur',
    'onkeydown',
    'onkeyup',
    'onkeypress',
    'onmousemove',
    'onmouseenter',
    'onmouseleave',
    'onsubmit',
    'onreset',
    'srcdoc',
    'xlink:href',
    'formaction',
  ],
};
