export const validRuntimeIconNames = [
  'Menu-bold',
  'R2D2',
  'accordion',
  'account-female',
  'account-files',
  'account-male',
  'account-target',
  'account-target-2',
  'activities',
  'address-lookup',
  'adjust',
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'app-ribbon',
  'app-ribbon_v3',
  'apps-drawer-closed',
  'apps-drawer-open',
  'archive',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'attachment',
  'bar-chart',
  'bills',
  'bitcoin',
  'bold',
  'bookmark',
  'box-minus',
  'box-minus-solid',
  'box-plus',
  'box-plus-solid',
  'bubble-chat-typing-1',
  'bubble-chat-typing-3',
  'building',
  'building-alt',
  'bullseye',
  'button',
  'button-group',
  'cab',
  'calculator',
  'calendar',
  'camera',
  'caret-down',
  'caret-left',
  'caret-right',
  'caret-up',
  'cases',
  'caution-knockout',
  'caution-solid',
  'chair',
  'checkbox',
  'checkbox-circle-alt',
  'checks',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'circle-checkmark',
  'circle-minus',
  'circle-plus',
  'circle-x',
  'class-category',
  'clock',
  'cloud',
  'cloud-install',
  'cloud-manage-apps_v1',
  'cloud-save',
  'cloud-sync',
  'code-css',
  'code-html',
  'coffee',
  'cog',
  'collapse',
  'collapse-alt',
  'columns',
  'contacts',
  'copy',
  'credit-memo',
  'currently_open',
  'customer-management',
  'customize',
  'dashboard',
  'date-picker-v2',
  'db-table',
  'decimals',
  'delete',
  'desktop',
  'dollar-bill',
  'double-chevron-left',
  'double-chevron-right',
  'dropdown',
  'edit',
  'edu',
  'email',
  'email-template',
  'estimate',
  'euro',
  'expand',
  'expand-alt',
  'external-link',
  'facebook',
  'facebook-alt',
  'fax',
  'file',
  'file-text',
  'filter',
  'flag_square',
  'flag_triangle',
  'flash-2',
  'folder-close',
  'folder-open',
  'gift',
  'globe',
  'google-plus',
  'google-plus-alt',
  'grid',
  'hide-visible',
  'home',
  'icon',
  'infinity',
  'info-sign',
  'institute',
  'integers',
  'invoice',
  'italic',
  'items-shelf',
  'laptop',
  'lightning',
  'link',
  'linkedin',
  'linkedin-alt',
  'list-ol',
  'list-ul',
  'location-arrow',
  'location-pin',
  'logo-circle-instagram',
  'logo-instagram',
  'logout',
  'm',
  'minus',
  'move',
  'navbar',
  'notifications',
  'ok',
  'opportunity',
  'pack-accounting-workflow',
  'pack-sales-pipeline',
  'pack-service-support',
  'pager',
  'paper-plane',
  'paste',
  'payment-terms',
  'paymentgateways',
  'paymentgateways_v2',
  'payments',
  'pen-write-v4',
  'permissions',
  'person-remove-2',
  'pet-dog-walk',
  'phone',
  'picture',
  'picture-alt',
  'pie-chart',
  'plane',
  'plus',
  'pound',
  'printer',
  'pushpin-horizontal',
  'pushpin-horizontal-pinned',
  'pushpin-vertical',
  'pushpin-vertical-pinned',
  'question',
  'quickbooks',
  'radio-buttons',
  'random',
  'receipts',
  'recurring-date',
  'redirect',
  'redo',
  'refresh',
  'remove',
  'rss',
  'rss-feed_v2',
  'salesrep-female',
  'salesrep-male',
  'save',
  'save-alt',
  'screens',
  'search',
  'section',
  'shield-fire',
  'small-remove',
  'smartphone-landscape',
  'smartphone-portrait',
  'soccer-ball',
  'square',
  'square-checkmark',
  'star-outline',
  'star-solid',
  'tab-group',
  'tablet-landscape',
  'tablet-portrait',
  'tag',
  'text',
  'text-input',
  'text-width',
  'ticket',
  'timer',
  'toggle',
  'tree',
  'trophy',
  'truck',
  'twitter',
  'twitter-alt',
  'underline',
  'undo',
  'upload-harddrive',
  'usd',
  'user-female',
  'user-male',
  'versions',
  'window-refresh',
  'yen',
  'zoom-in',
  'zoom-out',
  'text-v4',
  'calendar-v4',
  'landscape-image',
  'calendar-rounded-corners-V4',
  'synchronize-3',
  'chevron-up-V4',
  'chevron-down-V4',
  'add-circle-v4',
  'cloud-download-V4',
] as const;

export type RuntimeSvgIconName = (typeof validRuntimeIconNames)[number];

export type SvgIconData = {
  iconName: RuntimeSvgIconName;
  name: string;
  icon: string;
  keywords: string;
};

export type RuntimeIconLookUpDict = {
  [k in RuntimeSvgIconName]: SvgIconData;
};

export const iconComponentMap: RuntimeIconLookUpDict = {
  'Menu-bold': {
    iconName: 'Menu-bold',
    name: 'Menu Bold',
    icon: '',
    keywords: 'menu, navigation, hamburger',
  },
  R2D2: {
    iconName: 'R2D2',
    name: 'R2D2',
    icon: '',
    keywords: 'robot, star wars, droid',
  },
  refresh: {
    iconName: 'refresh',
    name: 'Refresh',
    icon: '',
    keywords: '',
  },
  plus: {
    iconName: 'plus',
    name: 'Plus',
    icon: '',
    keywords: '',
  },
  m: {
    iconName: 'm',
    name: 'Method',
    icon: '',
    keywords: 'M, m, ',
  },
  infinity: {
    iconName: 'infinity',
    name: 'Infinity',
    icon: '',
    keywords: '',
  },
  'folder-open': {
    iconName: 'folder-open',
    name: 'Folder',
    icon: '',
    keywords: 'Open',
  },
  'folder-close': {
    iconName: 'folder-close',
    name: 'Folder',
    icon: '',
    keywords: 'Close',
  },
  save: {
    iconName: 'save',
    name: 'Save',
    icon: '',
    keywords: '',
  },
  'save-alt': {
    iconName: 'save-alt',
    name: 'Save',
    icon: '',
    keywords: 'Alternate',
  },
  dashboard: {
    iconName: 'dashboard',
    name: 'Dashboard',
    icon: '',
    keywords: '',
  },
  currently_open: {
    iconName: 'currently_open',
    name: 'Currently Open',
    icon: '',
    keywords: '',
  },
  contacts: {
    iconName: 'contacts',
    name: 'Contacts',
    icon: '',
    keywords: '',
  },
  cog: {
    iconName: 'cog',
    name: 'Cog',
    icon: '',
    keywords: 'Gear',
  },
  cloud: {
    iconName: 'cloud',
    name: 'Cloud',
    icon: '',
    keywords: '',
  },
  'cloud-save': {
    iconName: 'cloud-save',
    name: 'Cloud',
    icon: '',
    keywords: 'Save / Upload',
  },
  'cloud-install': {
    iconName: 'cloud-install',
    name: 'Cloud',
    icon: '',
    keywords: 'Install',
  },
  'cloud-sync': {
    iconName: 'cloud-sync',
    name: 'Cloud',
    icon: '',
    keywords: 'Sync',
  },
  'cloud-manage-apps_v1': {
    iconName: 'cloud-manage-apps_v1',
    name: 'Manage Apps',
    icon: '',
    keywords: '',
  },
  'apps-drawer-open': {
    iconName: 'apps-drawer-open',
    name: 'App Drawer',
    icon: '',
    keywords: 'Open',
  },
  'apps-drawer-closed': {
    iconName: 'apps-drawer-closed',
    name: 'App Drawer',
    icon: '',
    keywords: 'Closed',
  },
  activities: {
    iconName: 'activities',
    name: 'Activities',
    icon: '',
    keywords: '',
  },
  laptop: {
    iconName: 'laptop',
    name: 'Laptop',
    icon: '',
    keywords: '',
  },
  desktop: {
    iconName: 'desktop',
    name: 'Desktop',
    icon: '',
    keywords: '',
  },
  'smartphone-landscape': {
    iconName: 'smartphone-landscape',
    name: 'Smartphone',
    icon: '',
    keywords: 'Landscape',
  },
  'smartphone-portrait': {
    iconName: 'smartphone-portrait',
    name: 'Smartphone',
    icon: '',
    keywords: 'Portrait',
  },
  'tablet-landscape': {
    iconName: 'tablet-landscape',
    name: 'Tablet',
    icon: '',
    keywords: 'Landscape',
  },
  'tablet-portrait': {
    iconName: 'tablet-portrait',
    name: 'Tablet',
    icon: '',
    keywords: 'Portrait',
  },
  'caret-up': {
    iconName: 'caret-up',
    name: 'Caret',
    icon: '',
    keywords: 'Up',
  },
  'caret-down': {
    iconName: 'caret-down',
    name: 'Caret',
    icon: '',
    keywords: 'Down',
  },
  'caret-left': {
    iconName: 'caret-left',
    name: 'Caret',
    icon: '',
    keywords: 'Left',
  },
  'caret-right': {
    iconName: 'caret-right',
    name: 'Caret',
    icon: '',
    keywords: 'Right',
  },
  calendar: {
    iconName: 'calendar',
    name: 'Calendar',
    icon: '',
    keywords: '',
  },
  'zoom-out': {
    iconName: 'zoom-out',
    name: 'Zoom',
    icon: '',
    keywords: 'Out',
  },
  'zoom-in': {
    iconName: 'zoom-in',
    name: 'Zoom',
    icon: '',
    keywords: 'In',
  },
  search: {
    iconName: 'search',
    name: 'Search',
    icon: '',
    keywords: '',
  },
  'user-male': {
    iconName: 'user-male',
    name: 'User',
    icon: '',
    keywords: 'Male',
  },
  'user-female': {
    iconName: 'user-female',
    name: 'User',
    icon: '',
    keywords: 'Female',
  },
  random: {
    iconName: 'random',
    name: 'Random',
    icon: '',
    keywords: '',
  },
  redirect: {
    iconName: 'redirect',
    name: 'Redirect',
    icon: '',
    keywords: '',
  },
  quickbooks: {
    iconName: 'quickbooks',
    name: 'QuickBooks',
    icon: '',
    keywords: 'QBO',
  },
  file: {
    iconName: 'file',
    name: 'File',
    icon: '',
    keywords: '',
  },
  'file-text': {
    iconName: 'file-text',
    name: 'File Text',
    icon: '',
    keywords: '',
  },
  question: {
    iconName: 'question',
    name: 'Question',
    icon: '',
    keywords: '',
  },
  delete: {
    iconName: 'delete',
    name: 'Delete',
    icon: '',
    keywords: 'Remove',
  },
  usd: {
    iconName: 'usd',
    name: 'Dollar',
    icon: '',
    keywords: 'USD',
  },
  'chevron-left': {
    iconName: 'chevron-left',
    name: 'Chevron',
    icon: '',
    keywords: 'Left',
  },
  'chevron-right': {
    iconName: 'chevron-right',
    name: 'Chevron',
    icon: '',
    keywords: 'Right',
  },
  'chevron-up': {
    iconName: 'chevron-up',
    name: 'Chevron',
    icon: '',
    keywords: 'Up',
  },
  'chevron-down': {
    iconName: 'chevron-down',
    name: 'Chevron',
    icon: '',
    keywords: 'Down',
  },
  'double-chevron-right': {
    iconName: 'double-chevron-right',
    name: 'Double Chevron',
    icon: '',
    keywords: 'Right',
  },
  'double-chevron-left': {
    iconName: 'double-chevron-left',
    name: 'Double Chevron',
    icon: '',
    keywords: 'Left',
  },
  logout: {
    iconName: 'logout',
    name: 'Logout',
    icon: '',
    keywords: '',
  },
  edit: {
    iconName: 'edit',
    name: 'Edit',
    icon: '',
    keywords: '',
  },
  remove: {
    iconName: 'remove',
    name: 'Remove',
    icon: '',
    keywords: '',
  },
  ok: {
    iconName: 'ok',
    name: 'OK',
    icon: '',
    keywords: '',
  },
  paymentgateways: {
    iconName: 'paymentgateways',
    name: 'Payment Gateway',
    icon: '',
    keywords: '',
  },
  paymentgateways_v2: {
    iconName: 'paymentgateways_v2',
    name: 'Payment Gateway',
    icon: '',
    keywords: 'Alternate',
  },
  navbar: {
    iconName: 'navbar',
    name: 'Navbar',
    icon: '',
    keywords: '',
  },
  minus: {
    iconName: 'minus',
    name: 'Minus',
    icon: '',
    keywords: '',
  },
  grid: {
    iconName: 'grid',
    name: 'Grid',
    icon: '',
    keywords: '',
  },
  filter: {
    iconName: 'filter',
    name: 'Filter',
    icon: '',
    keywords: '',
  },
  email: {
    iconName: 'email',
    name: 'Email',
    icon: '',
    keywords: '',
  },
  dropdown: {
    iconName: 'dropdown',
    name: 'Dropdown Menu',
    icon: '',
    keywords: '',
  },
  'db-table': {
    iconName: 'db-table',
    name: 'Database DB Table',
    icon: '',
    keywords: '',
  },
  copy: {
    iconName: 'copy',
    name: 'Copy',
    icon: '',
    keywords: '',
  },
  'circle-x': {
    iconName: 'circle-x',
    name: 'Circle',
    icon: '',
    keywords: 'X',
  },
  'circle-plus': {
    iconName: 'circle-plus',
    name: 'Circle',
    icon: '',
    keywords: 'Plus',
  },
  'circle-minus': {
    iconName: 'circle-minus',
    name: 'Circle',
    icon: '',
    keywords: 'Minus',
  },
  'circle-checkmark': {
    iconName: 'circle-checkmark',
    name: 'Circle',
    icon: '',
    keywords: 'Checkmark',
  },
  checkbox: {
    iconName: 'checkbox',
    name: 'Checkbox',
    icon: '',
    keywords: '',
  },
  button: {
    iconName: 'button',
    name: 'Button',
    icon: '',
    keywords: '',
  },
  'button-group': {
    iconName: 'button-group',
    name: 'Button',
    icon: '',
    keywords: 'Group',
  },
  'box-plus-solid': {
    iconName: 'box-plus-solid',
    name: 'Box Plus',
    icon: '',
    keywords: 'Solid',
  },
  'box-plus': {
    iconName: 'box-plus',
    name: 'Box Plus',
    icon: '',
    keywords: 'Outline',
  },
  'box-minus-solid': {
    iconName: 'box-minus-solid',
    name: 'Box Minus',
    icon: '',
    keywords: 'Solid',
  },
  'box-minus': {
    iconName: 'box-minus',
    name: 'Box Minus',
    icon: '',
    keywords: 'Outline',
  },
  'app-ribbon': {
    iconName: 'app-ribbon',
    name: 'App Ribbon',
    icon: '',
    keywords: '',
  },
  accordion: {
    iconName: 'accordion',
    name: 'Accordion Menu',
    icon: '',
    keywords: '',
  },
  'code-css': {
    iconName: 'code-css',
    name: 'Code',
    icon: '',
    keywords: 'CSS',
  },
  'code-html': {
    iconName: 'code-html',
    name: 'Code',
    icon: '',
    keywords: 'HTML',
  },
  'star-solid': {
    iconName: 'star-solid',
    name: 'Star',
    icon: '',
    keywords: 'Solid',
  },
  'star-outline': {
    iconName: 'star-outline',
    name: 'Star',
    icon: '',
    keywords: 'Outline',
  },
  'tab-group': {
    iconName: 'tab-group',
    name: 'Tab Group',
    icon: '',
    keywords: '',
  },
  text: {
    iconName: 'text',
    name: 'Text',
    icon: '',
    keywords: '',
  },
  'text-input': {
    iconName: 'text-input',
    name: 'Text Input',
    icon: '',
    keywords: '',
  },
  section: {
    iconName: 'section',
    name: 'Section',
    icon: '',
    keywords: '',
  },
  toggle: {
    iconName: 'toggle',
    name: 'Toggle',
    icon: '',
    keywords: '',
  },
  versions: {
    iconName: 'versions',
    name: 'Versions',
    icon: '',
    keywords: '',
  },
  screens: {
    iconName: 'screens',
    name: 'Screens',
    icon: '',
    keywords: '',
  },
  attachment: {
    iconName: 'attachment',
    name: 'Attachment',
    icon: '',
    keywords: '',
  },
  timer: {
    iconName: 'timer',
    name: 'Timer',
    icon: '',
    keywords: '',
  },
  tag: {
    iconName: 'tag',
    name: 'Tag',
    icon: '',
    keywords: '',
  },
  rss: {
    iconName: 'rss',
    name: 'RSS',
    icon: '',
    keywords: '',
  },
  'rss-feed_v2': {
    iconName: 'rss-feed_v2',
    name: 'RSS',
    icon: '',
    keywords: 'Alternate',
  },
  flag_triangle: {
    iconName: 'flag_triangle',
    name: 'Flag',
    icon: '',
    keywords: 'Triangle',
  },
  flag_square: {
    iconName: 'flag_square',
    name: 'Flag',
    icon: '',
    keywords: 'Square',
  },
  customize: {
    iconName: 'customize',
    name: 'Customize',
    icon: '',
    keywords: '',
  },
  archive: {
    iconName: 'archive',
    name: 'Archive',
    icon: '',
    keywords: '',
  },
  'app-ribbon_v3': {
    iconName: 'app-ribbon_v3',
    name: 'App Ribbon',
    icon: '',
    keywords: '',
  },
  'pen-write-v4': {
    iconName: 'pen-write-v4',
    name: 'Signature',
    icon: '',
    keywords: '',
  },
  'address-lookup': {
    iconName: 'address-lookup',
    name: 'Address Lookup',
    icon: '',
    keywords: '',
  },
  'radio-buttons': {
    iconName: 'radio-buttons',
    name: 'Radio Buttons',
    icon: '',
    keywords: '',
  },
  notifications: {
    iconName: 'notifications',
    name: 'Notifications',
    icon: '',
    keywords: '',
  },
  picture: {
    iconName: 'picture',
    name: 'Picture',
    icon: '',
    keywords: '',
  },
  'picture-alt': {
    iconName: 'picture-alt',
    name: 'Picture',
    icon: '',
    keywords: 'Alternate',
  },
  camera: {
    iconName: 'camera',
    name: 'Camera',
    icon: '',
    keywords: '',
  },
  permissions: {
    iconName: 'permissions',
    name: 'Permissions',
    icon: '',
    keywords: '',
  },
  undo: {
    iconName: 'undo',
    name: 'Undo',
    icon: '',
    keywords: '',
  },
  redo: {
    iconName: 'redo',
    name: 'Redo',
    icon: '',
    keywords: '',
  },
  'pushpin-vertical': {
    iconName: 'pushpin-vertical',
    name: 'Push Pin Vertical',
    icon: '',
    keywords: '',
  },
  'pushpin-vertical-pinned': {
    iconName: 'pushpin-vertical-pinned',
    name: 'Push Pin Vertical',
    icon: '',
    keywords: 'Pinned',
  },
  'pushpin-horizontal': {
    iconName: 'pushpin-horizontal',
    name: 'Push Pin Horizontal',
    icon: '',
    keywords: '',
  },
  'pushpin-horizontal-pinned': {
    iconName: 'pushpin-horizontal-pinned',
    name: 'Push Pin Horizontal',
    icon: '',
    keywords: 'Pinned',
  },
  lightning: {
    iconName: 'lightning',
    name: 'Lightning',
    icon: '',
    keywords: '',
  },
  'flash-2': {
    iconName: 'flash-2',
    name: 'Lightning Alt',
    icon: '',
    keywords: '',
  },
  integers: {
    iconName: 'integers',
    name: 'Integers',
    icon: '',
    keywords: '',
  },
  decimals: {
    iconName: 'decimals',
    name: 'Decimals',
    icon: '',
    keywords: '',
  },
  icon: {
    iconName: 'icon',
    name: 'Icon',
    icon: '',
    keywords: '',
  },
  columns: {
    iconName: 'columns',
    name: 'Columns',
    icon: '',
    keywords: '',
  },
  'arrow-up': {
    iconName: 'arrow-up',
    name: 'Arrow',
    icon: '',
    keywords: 'Up',
  },
  'arrow-right': {
    iconName: 'arrow-right',
    name: 'Arrow',
    icon: '',
    keywords: 'Right',
  },
  'arrow-down': {
    iconName: 'arrow-down',
    name: 'Arrow',
    icon: '',
    keywords: 'Down',
  },
  'arrow-left': {
    iconName: 'arrow-left',
    name: 'Arrow',
    icon: '',
    keywords: 'Left',
  },
  'caution-solid': {
    iconName: 'caution-solid',
    name: 'Caution',
    icon: '',
    keywords: '',
  },
  'caution-knockout': {
    iconName: 'caution-knockout',
    name: 'Caution',
    icon: '',
    keywords: 'Alternate',
  },
  expand: {
    iconName: 'expand',
    name: 'Expand',
    icon: '',
    keywords: '',
  },
  'expand-alt': {
    iconName: 'expand-alt',
    name: 'Expand',
    icon: '',
    keywords: 'Alternate',
  },
  collapse: {
    iconName: 'collapse',
    name: 'Collapse',
    icon: '',
    keywords: '',
  },
  'collapse-alt': {
    iconName: 'collapse-alt',
    name: 'Collapse',
    icon: '',
    keywords: 'Alternate',
  },
  opportunity: {
    iconName: 'opportunity',
    name: 'Opportunity',
    icon: '',
    keywords: '',
  },
  'list-ul': {
    iconName: 'list-ul',
    name: 'List',
    icon: '',
    keywords: 'UL',
  },
  'list-ol': {
    iconName: 'list-ol',
    name: 'List',
    icon: '',
    keywords: 'OL',
  },
  invoice: {
    iconName: 'invoice',
    name: 'Invoice',
    icon: '',
    keywords: '',
  },
  clock: {
    iconName: 'clock',
    name: 'Clock',
    icon: '',
    keywords: '',
  },
  'hide-visible': {
    iconName: 'hide-visible',
    name: 'Hide Visible',
    icon: '',
    keywords: '',
  },
  'recurring-date': {
    iconName: 'recurring-date',
    name: 'Recurring Date',
    icon: '',
    keywords: '',
  },
  'date-picker-v2': {
    iconName: 'date-picker-v2',
    name: 'Date Picker',
    icon: '',
    keywords: '',
  },
  'pie-chart': {
    iconName: 'pie-chart',
    name: 'Pie Chart',
    icon: '',
    keywords: '',
  },
  building: {
    iconName: 'building',
    name: 'Building',
    icon: '',
    keywords: '',
  },
  'building-alt': {
    iconName: 'building-alt',
    name: 'Building',
    icon: '',
    keywords: 'Alternate',
  },
  cab: {
    iconName: 'cab',
    name: 'Cab',
    icon: '',
    keywords: '',
  },
  calculator: {
    iconName: 'calculator',
    name: 'Calculator',
    icon: '',
    keywords: '',
  },
  coffee: {
    iconName: 'coffee',
    name: 'Coffee Cup',
    icon: '',
    keywords: '',
  },
  'dollar-bill': {
    iconName: 'dollar-bill',
    name: 'Dollar Bill',
    icon: '',
    keywords: '',
  },
  edu: {
    iconName: 'edu',
    name: 'Education',
    icon: '',
    keywords: '',
  },
  euro: {
    iconName: 'euro',
    name: 'Euro',
    icon: '',
    keywords: '',
  },
  gift: {
    iconName: 'gift',
    name: 'Gift',
    icon: '',
    keywords: '',
  },
  globe: {
    iconName: 'globe',
    name: 'Globe',
    icon: '',
    keywords: '',
  },
  home: {
    iconName: 'home',
    name: 'Home',
    icon: '',
    keywords: '',
  },
  institute: {
    iconName: 'institute',
    name: 'Institute',
    icon: '',
    keywords: '',
  },
  'paper-plane': {
    iconName: 'paper-plane',
    name: 'Paper Plane',
    icon: '',
    keywords: '',
  },
  phone: {
    iconName: 'phone',
    name: 'Phone',
    icon: '',
    keywords: '',
  },
  plane: {
    iconName: 'plane',
    name: 'Plane',
    icon: '',
    keywords: '',
  },
  pound: {
    iconName: 'pound',
    name: 'GBP Pound',
    icon: '',
    keywords: '',
  },
  'soccer-ball': {
    iconName: 'soccer-ball',
    name: 'Soccer Ball',
    icon: '',
    keywords: '',
  },
  ticket: {
    iconName: 'ticket',
    name: 'Ticket',
    icon: '',
    keywords: '',
  },
  tree: {
    iconName: 'tree',
    name: 'Tree',
    icon: '',
    keywords: '',
  },
  trophy: {
    iconName: 'trophy',
    name: 'Trophy',
    icon: '',
    keywords: '',
  },
  truck: {
    iconName: 'truck',
    name: 'Truck',
    icon: '',
    keywords: '',
  },
  yen: {
    iconName: 'yen',
    name: 'Yen',
    icon: '',
    keywords: '',
  },
  bitcoin: {
    iconName: 'bitcoin',
    name: 'Bitcoin',
    icon: '',
    keywords: '',
  },
  move: {
    iconName: 'move',
    name: 'Move',
    icon: '',
    keywords: '',
  },
  'info-sign': {
    iconName: 'info-sign',
    name: 'Info Sign',
    icon: '',
    keywords: '',
  },
  adjust: {
    iconName: 'adjust',
    name: 'Adjust',
    icon: '',
    keywords: '',
  },
  bookmark: {
    iconName: 'bookmark',
    name: 'Bookmark',
    icon: '',
    keywords: '',
  },
  'location-arrow': {
    iconName: 'location-arrow',
    name: 'Location Arrow',
    icon: '',
    keywords: '',
  },
  'bar-chart': {
    iconName: 'bar-chart',
    name: 'Bar Chart',
    icon: '',
    keywords: '',
  },
  'align-center': {
    iconName: 'align-center',
    name: 'Align',
    icon: '',
    keywords: 'Center',
  },
  'align-justify': {
    iconName: 'align-justify',
    name: 'Align',
    icon: '',
    keywords: 'Justify',
  },
  'align-left': {
    iconName: 'align-left',
    name: 'Align',
    icon: '',
    keywords: 'Left',
  },
  'align-right': {
    iconName: 'align-right',
    name: 'Align',
    icon: '',
    keywords: 'Right',
  },
  'text-width': {
    iconName: 'text-width',
    name: 'Text Width',
    icon: '',
    keywords: '',
  },
  link: {
    iconName: 'link',
    name: 'Link',
    icon: '',
    keywords: '',
  },
  bold: {
    iconName: 'bold',
    name: 'Bold',
    icon: '',
    keywords: '',
  },
  italic: {
    iconName: 'italic',
    name: 'Italic',
    icon: '',
    keywords: '',
  },
  underline: {
    iconName: 'underline',
    name: 'Underline',
    icon: '',
    keywords: '',
  },
  facebook: {
    iconName: 'facebook',
    name: 'Facebook',
    icon: '',
    keywords: '',
  },
  'facebook-alt': {
    iconName: 'facebook-alt',
    name: 'Facebook',
    icon: '',
    keywords: 'Alternate',
  },
  'google-plus': {
    iconName: 'google-plus',
    name: 'Google Plus',
    icon: '',
    keywords: '',
  },
  'google-plus-alt': {
    iconName: 'google-plus-alt',
    name: 'Google Plus',
    icon: '',
    keywords: 'Alternate',
  },
  linkedin: {
    iconName: 'linkedin',
    name: 'LinkedIn',
    icon: '',
    keywords: '',
  },
  'linkedin-alt': {
    iconName: 'linkedin-alt',
    name: 'LinkedIn',
    icon: '',
    keywords: 'Alternate',
  },
  twitter: {
    iconName: 'twitter',
    name: 'Twitter',
    icon: '',
    keywords: '',
  },
  'twitter-alt': {
    iconName: 'twitter-alt',
    name: 'Twitter',
    icon: '',
    keywords: 'Alternate',
  },
  fax: {
    iconName: 'fax',
    name: 'Fax',
    icon: '',
    keywords: '',
  },
  'external-link': {
    iconName: 'external-link',
    name: 'Portal',
    icon: '',
    keywords: 'External Link',
  },
  bullseye: {
    iconName: 'bullseye',
    name: 'Bullseye',
    icon: '',
    keywords: '',
  },
  'person-remove-2': {
    iconName: 'person-remove-2',
    name: 'Remove Contacts',
    icon: '',
    keywords: '',
  },
  square: {
    iconName: 'square',
    name: 'Square',
    icon: '',
    keywords: '',
  },
  'square-checkmark': {
    iconName: 'square-checkmark',
    name: 'Square checkmark',
    icon: '',
    keywords: '',
  },
  'account-female': {
    iconName: 'account-female',
    name: 'Account',
    icon: '',
    keywords: 'Female',
  },
  'account-male': {
    iconName: 'account-male',
    name: 'Account',
    icon: '',
    keywords: 'Male',
  },
  bills: {
    iconName: 'bills',
    name: 'Bills',
    icon: '',
    keywords: '',
  },
  cases: {
    iconName: 'cases',
    name: 'Cases',
    icon: '',
    keywords: '',
  },
  checks: {
    iconName: 'checks',
    name: 'Checks',
    icon: '',
    keywords: '',
  },
  'class-category': {
    iconName: 'class-category',
    name: 'Class Category',
    icon: '',
    keywords: '',
  },
  'credit-memo': {
    iconName: 'credit-memo',
    name: 'Credit Memo',
    icon: '',
    keywords: '',
  },
  'email-template': {
    iconName: 'email-template',
    name: 'Email Template',
    icon: '',
    keywords: '',
  },
  'items-shelf': {
    iconName: 'items-shelf',
    name: 'Items Shelf',
    icon: '',
    keywords: '',
  },
  'payment-terms': {
    iconName: 'payment-terms',
    name: 'Payment',
    icon: '',
    keywords: 'Payment Terms',
  },
  payments: {
    iconName: 'payments',
    name: 'Payments',
    icon: '',
    keywords: '',
  },
  estimate: {
    iconName: 'estimate',
    name: 'Estimates',
    icon: '',
    keywords: '',
  },
  printer: {
    iconName: 'printer',
    name: 'Printer',
    icon: '',
    keywords: '',
  },
  'customer-management': {
    iconName: 'customer-management',
    name: 'Customer Management',
    icon: '',
    keywords: '',
  },
  'pack-accounting-workflow': {
    iconName: 'pack-accounting-workflow',
    name: 'Accounting Workflow',
    icon: '',
    keywords: '',
  },
  'pack-sales-pipeline': {
    iconName: 'pack-sales-pipeline',
    name: 'Sales Pipleline',
    icon: '',
    keywords: '',
  },
  'pack-service-support': {
    iconName: 'pack-service-support',
    name: 'Service Support',
    icon: '',
    keywords: '',
  },
  'salesrep-male': {
    iconName: 'salesrep-male',
    name: 'Sales Rep',
    icon: '',
    keywords: 'Male',
  },
  'salesrep-female': {
    iconName: 'salesrep-female',
    name: 'Sales Rep',
    icon: '',
    keywords: 'Female',
  },
  pager: {
    iconName: 'pager',
    name: 'Pager',
    icon: '',
    keywords: '',
  },
  paste: {
    iconName: 'paste',
    name: 'Paste',
    icon: '',
    keywords: '',
  },
  'account-files': {
    iconName: 'account-files',
    name: 'Account Files',
    icon: '',
    keywords: '',
  },
  chair: {
    iconName: 'chair',
    name: 'Chair',
    icon: '',
    keywords: '',
  },
  'logo-circle-instagram': {
    iconName: 'logo-circle-instagram',
    name: 'Instagram',
    icon: '',
    keywords: 'Instagram Circle',
  },
  'logo-instagram': {
    iconName: 'logo-instagram',
    name: 'Instagram',
    icon: '',
    keywords: '',
  },
  'pet-dog-walk': {
    iconName: 'pet-dog-walk',
    name: 'Walk Dog',
    icon: '',
    keywords: 'Pet',
  },
  receipts: {
    iconName: 'receipts',
    name: 'Receipt',
    icon: '',
    keywords: '',
  },
  'shield-fire': {
    iconName: 'shield-fire',
    name: 'Fire Shield',
    icon: '',
    keywords: 'Shield',
  },
  'small-remove': {
    iconName: 'small-remove',
    name: 'Remove Circle',
    icon: '',
    keywords: 'Remove',
  },
  'location-pin': {
    iconName: 'location-pin',
    name: 'Location',
    icon: '',
    keywords: 'Map Pin',
  },
  'upload-harddrive': {
    iconName: 'upload-harddrive',
    name: 'Hard Drive',
    icon: '',
    keywords: 'Upload',
  },
  'account-target': {
    iconName: 'account-target',
    name: 'Account Target',
    icon: '',
    keywords: '',
  },
  'account-target-2': {
    iconName: 'account-target-2',
    name: 'Account Target Solid',
    icon: '',
    keywords: '',
  },
  'checkbox-circle-alt': {
    iconName: 'checkbox-circle-alt',
    name: 'Checkbox Solid',
    icon: '',
    keywords: 'Circle',
  },
  'window-refresh': {
    iconName: 'window-refresh',
    name: 'Window Refresh',
    icon: '',
    keywords: 'Window, Refresh',
  },
  'bubble-chat-typing-1': {
    iconName: 'bubble-chat-typing-1',
    name: 'Chat',
    icon: '',
    keywords: 'Typing (Square)',
  },
  'bubble-chat-typing-3': {
    iconName: 'bubble-chat-typing-3',
    name: 'Chat',
    icon: '',
    keywords: 'Typing (Round)',
  },
  'text-v4': {
    iconName: 'text-v4',
    name: 'Text V4',
    icon: '',
    keywords: 'Text',
  },
  'calendar-v4': {
    iconName: 'calendar-v4',
    name: 'Calendar V4',
    icon: '',
    keywords: 'Calendar',
  },
  'landscape-image': {
    iconName: 'landscape-image',
    name: 'Landscape Image',
    icon: '',
    keywords: 'Image',
  },
  'synchronize-3': {
    iconName: 'synchronize-3',
    name: 'Synchronize 3',
    icon: '',
    keywords: 'Sync',
  },
  'calendar-rounded-corners-V4': {
    iconName: 'calendar-rounded-corners-V4',
    name: 'Calendar Rounded Corners V4',
    icon: '',
    keywords: 'Calendar',
  },
  'chevron-up-V4': {
    iconName: 'chevron-up-V4',
    name: 'Chevron Up V4',
    icon: '',
    keywords: 'Chevron, Up',
  },
  'chevron-down-V4': {
    iconName: 'chevron-down-V4',
    name: 'Chevron Down V4',
    icon: '',
    keywords: 'Chevron, Down',
  },
  'add-circle-v4': {
    iconName: 'add-circle-v4',
    name: 'Add Circle V4',
    icon: '',
    keywords: 'Add, Circle',
  },
  'cloud-download-V4': {
    iconName: 'cloud-download-V4',
    name: 'Cloud Download V4',
    icon: '',
    keywords: 'Cloud, Download',
  },
};
