// NOTE: If you are a dev intending to work on the React Wrapper version of action-editor,
// DO NOT EDIT THIS FILE. Instead start at the entrypoint-for-react-wrapper.js and work
// your way from there.
// Code for registering npm packages to be imported into the angular app
import { react2angular } from 'react2angular';
import SvgIcon from '@m-next/svg-icon';
import ActionEditorCopilot from '@m-next/action-editor-copilot';
import miaeButton from './old-components/button-dir.js';
/* eslint-disable-next-line @typescript-eslint/no-require-imports, no-undef */
require("./old-externals/angucomplete-alt.min.js");

// Action-Editor Services
import noSqlSvc from './services/nosql.js';
import currentScreenSvc from './services/current-screen';
import editorSvc from './services/editor';
import editorApiSvc from './services/editor-api.js';
import editorValidationSvc from './services/editor-validation.js';
import screenToJsonSvc from './services/screen-to-json.js';
import deleteModalSvc from './services/delete-modal.js';
import renameModalSvc from './services/rename-modal.js';
import usedControlsSvc from './services/used-controls.js';
// Top-level Models
import BaseModel from './models/base.js';
import EditorModel from './models/editor.js';
import ActionSetModel from './models/action-set.js';
import ResultToSetModel from './models/result-to-set.js';
import ComplexValueModel from './models/complex-value.js';
import ControlModel from './models/control.js';
// Action Editor Directive (Component)
import ActionEditorDir from './editor-dir';
//  ActionEditor Sub-Directives (Sub-Components)
import miActionDescription from './components/action-description-dir.js'
import miActionList from './components/action-list-dir.js'
import miActionNotes from './components/action-notes-dir.js'
import miComplexValue from './components/complex-value-dir.js'
import miControlActionItem from './components/control-action-item-dir.js'
import miFieldSelect from './components/field-select-dir.js'
import miMoreOptionsMenu from './components/more-options-menu-dir.js'
import miResultToSet from './components/result-to-set-dir.js'
import miValidationClass from './components/validation-class-dir.js'
import miCriteriaString from './components/criteria-string-dir.js'
import miExpressionBuilder from './components/expression-builder-dir.js'
// Action Editor Controller
import ActionEditorCtrl from './editor-ctrl';
// Actions
import ActionResultModel from './actions/action-result/model.js'
import ActionResultCtrl from './actions/action-result/ctrl.js'
import ConditionalModel from './actions/conditional-statement/model.js'
import ConditionalStatementCtrl from './actions/conditional-statement/ctrl.js'
import ShowMessageModel from './actions/show-message/model.js'
import ShowMessageCtrl from './actions/show-message/ctrl.js'
import UpdateControlsModel from './actions/update-controls/model.js'
import UpdateControlsCtrl from './actions/update-controls/ctrl.js'
import SaveAllModel from './actions/save-all/model.js'
import SaveAllCtrl from './actions/save-all/ctrl.js'
import InsertRecordModel from './actions/insert-record/model.js'
import InsertRecordCtrl from './actions/insert-record/ctrl.js'
import UpdateRecordModel from './actions/update-record/model.js'
import UpdateRecordCtrl from './actions/update-record/ctrl.js'
import SetActiveRecordModel from './actions/set-active-record/model.js'
import SetActiveRecordCtl from './actions/set-active-record/ctrl.js'
import TextFunctionsModel from './actions/text-functions/model.js'
import TextFunctionsCtrl from './actions/text-functions/ctrl.js'
import MathFunctionsModel from './actions/math-functions/model.js'
import MathFunctionsCtrl from './actions/math-functions/ctrl.js'
import ShowHideControlsModel from './actions/show-hide-controls/model.js'
import ShowHideControlCtrl from './actions/show-hide-controls/ctrl.js'
import EnableDisableControlsModel from './actions/enable-disable/model.js'
import EnableDisableControlCtrl from './actions/enable-disable/ctrl.js'
import SetControlFocusModel from './actions/control-focus/model.js'
import SetControlFocusCtrl from './actions/control-focus/ctrl.js'
import ClearScreenModel from './actions/clear-screen/model.js';
import ClearScreenCtrl from './actions/clear-screen/ctrl.js';
import GoToScreenModel from './actions/goto-screen/model.js'
import GoToScreenCtrl from './actions/goto-screen/ctrl.js'
import RefreshControlModel from './actions/refresh-control/model.js'
import RefreshControlCtrl from './actions/refresh-control/ctrl.js'
import SetViewFilterModel from './actions/set-view-filter/model.js'
import SetViewFilterCtrl from './actions/set-view-filter/ctrl.js'
import DateFunctionsModel from './actions/date-functions/model.js'
import DateFunctionsCtrl from './actions/date-functions/ctrl.js'
import SendEmailModel from './actions/send-email/model.js'
import SendEmailCtrl from './actions/send-email/ctrl.js'
import CheckPermissionModel from './actions/check-permission/model.js'
import CheckPermissionCtrl from './actions/check-permission/ctrl.js'
import GenerateReportModel from './actions/generate-report/model.js'
import GenerateReportCtrl from './actions/generate-report/ctrl.js'
import DeleteRecordModel from './actions/delete-record/model.js'
import DeleteRecordCtrl from './actions/delete-record/ctrl.js'
import RetrieveValuesModel from './actions/retrieve-values/model.js'
import RetrieveValuesCtrl from './actions/retrieve-values/ctrl.js'
import CreateShortUrlModel from './actions/short-url/model.js'
import CreateShortUrlCtrl from './actions/short-url/ctrl.js'
import CallWebServiceModel from './actions/call-webservice/model.js'
import CallWebServiceCtrl from './actions/call-webservice/ctrl.js'
import StopProcessingModel from './actions/stop-processing/model.js'
import StopProcessingCtrl from './actions/stop-processing/ctrl.js'
import LoopThroughTableModel from './actions/loop-through-table/model.js'
import LoopThroughTableCtrl from './actions/loop-through-table/ctrl.js'
import PrepareAccountingModel from './actions/prepare-accounting/model.js'
import PrepareAccountingCtrl from './actions/prepare-accounting/ctrl.js'
import ProcessPaymentsCtrl from './actions/payment-processing/ctrl.js'
import ProcessPaymentsModel from './actions/payment-processing/model.js'
import ProcessPaymentsV2Ctrl from './actions/process-payments-v2/ctrl.js'
import ProcessPaymentsV2Model from './actions/process-payments-v2/model.js'
import LoopThroughGridModel from './actions/loop-through-grid/model.js'
import LoopThroughGridCtrl from './actions/loop-through-grid/ctrl.js'
import CallActionSetModel from './actions/call-action-set/model.js'
import CallActionSetCtrl from './actions/call-action-set/ctrl.js'
import SharedResultModel from './actions/shared-result/model.js'
import SharedResultCtrl from './actions/shared-result/ctrl.js'
import GoToWebpageModel from './actions/goto-webpage/model.js'
import GoToWebpageCtrl from './actions/goto-webpage/ctrl.js'
import ExpandCollapseSectionModel from './actions/expand-collapse-section/model.js'
import ExpandCollapseSectionCtrl from './actions/expand-collapse-section/ctrl.js'
import ShowRightPanelModel from './actions/show-right-panel/model.js'
import ShowRightPanelCtrl from './actions/show-right-panel/ctrl.js'
import ValidateControlsModel from './actions/validate-controls/model.js'
import ValidateControlsCtrl from './actions/validate-controls/ctrl.js'
import LoopThroughDocumentsModel from './actions/loop-through-documents/model.js'
import LoopThroughDocumentsCtrl from './actions/loop-through-documents/ctrl.js'
import LoopThroughListModel from './actions/loop-through-list/model.js'
import LoopThroughListCtrl from './actions/loop-through-list/ctrl.js'
import AddAttachmentModel from './actions/add-attachment/model.js'
import AddAttachmentCtrl from './actions/add-attachment/ctrl.js'
import RetrieveValuesFromEmailModel from './actions/retrieve-from-email/model.js'
import RetrieveValuesFromEmailCtrl from './actions/retrieve-from-email/ctrl.js'
import IsReadOnlyModel from './actions/is-readonly/model.js'
import IsReadOnlyCtrl from './actions/is-readonly/ctrl.js'
import RetrieveExchangeRateModel from './actions/retrieve-exchange-rate/model.js'
import RetrieveExchangeRateCtrl from './actions/retrieve-exchange-rate/ctrl.js'
import CurrencyConversionModel from './actions/currency-conversion/model.js'
import CurrencyConversionCtrl from './actions/currency-conversion/ctrl.js'
import MergeEntitiesModel from './actions/merge-entities/model.js'
import MergeEntitiesCtrl from './actions/merge-entities/ctrl.js'
import MappingModel from './actions/mapping/model.js'
import MappingCtrl from './actions/mapping/ctrl.js'
// Mobile and SMS
import SendMobilePushNotificationModel from './actions/send-mobile-push-notification/model.js'
import SendMobilePushNotificationCtrl from './actions/send-mobile-push-notification/ctrl.js'
import SendSmsModel from './actions/send-sms/model.js'
import SendSmsCtrl from './actions/send-sms/ctrl.js'
import OpenPopUpModel from './actions/open-popup/model.js';
import OpenPopUpCtrl from './actions/open-popup/ctrl.js';
import ClosePopUpModel from './actions/close-popup/model.js';
import ClosePopUpCtrl from './actions/close-popup/ctrl.js';
import ShowToastModel from './actions/show-toast/model.js';
import ShowToastCtrl from './actions/show-toast/ctrl.js';

// mi Jquery components
import miDatePicker from './old-components/datepicker-dir.js';

// Criteria Builder
import aeCriteriaBuilderModel from "./criteriaBuilder/model.js";
import aeCriteriaBuilderSvc from "./criteriaBuilder/criteria-svc.js";
import miaeCriteriaBuilder from "./criteriaBuilder/builder-dir.js";
import miaeCriteriaStatement from "./criteriaBuilder/statement-dir.js";
import miaeCriteriaRow from "./criteriaBuilder/row-dir.js";

const registrations = () => {
    // The requires push is so that we don't blow away whats already set to the method angular module
    angular.module("method").requires.push("angucomplete-alt");
    // angular.module("method").requires.push("ngSanitize");
    angular.module("method")
        // .config(function ($sceProvider) {
        //     $sceProvider.enabled(false);
        // })

        // retro-fit of SvgIcon must go early.
        .component(
            'svgIcon',
            react2angular(SvgIcon, [
                'className',
                'color',
                'hoverColor',
                'iconRef',
                'style',
                'id',
                'testId',
                'name',
                'offsetX',
                'offsetY',
                'onClick',
                'size',
                'stroke',
                'strokeWidth',
                'viewBox',
                'isV4Design',
                'rotate',
                'caption',
                'disabled',
                'tabIndex',
                'backgroundColor',
                'isRound',
                'forwardRef',
                'title',
                'tooltip',
                'tooltipId',
                'border',
                'children',
                'onKeyUp'
            ])
        )
        
        .component(
            'actionEditorCopilot',
            react2angular(ActionEditorCopilot, [
                'open',
                'authToken',
                'authTokenV2',
                'screenId',
                'versionId',
                'eventId',
                'accountName',
                'onActionSetReplace'
            ])
        )

        .directive("miaeButton", miaeButton)
        .directive("miDatePicker", miDatePicker)

        .factory("currentScreenSvc", currentScreenSvc)
        .factory("noSqlSvc", noSqlSvc)
        .factory("editorSvc", editorSvc)
        .factory("editorApiSvc", editorApiSvc)
        .factory("editorValidationSvc", editorValidationSvc)
        .factory("screenToJsonSvc", screenToJsonSvc)
        .factory("deleteModalSvc", deleteModalSvc)
        .factory("renameModalSvc", renameModalSvc)
        .factory("usedControlsSvc", usedControlsSvc)

        .factory("BaseModel", BaseModel)
        .factory("EditorModel", EditorModel)
        .factory("ActionSetModel", ActionSetModel)
        .factory("ResultToSetModel", ResultToSetModel)
        .factory("ComplexValueModel", ComplexValueModel)
        .factory("ControlModel", ControlModel)

        .directive("miActionEditor", ActionEditorDir)

        .directive("miActionDescription", miActionDescription)
        .directive("miActionList", miActionList)
        .directive("miActionNotes", miActionNotes)
        .directive("miComplexValue", miComplexValue)
        .directive("miControlActionItem", miControlActionItem)
        .directive("miFieldSelect", miFieldSelect)
        .directive("miMoreOptionsMenu", miMoreOptionsMenu)
        .directive("miResultToSet", miResultToSet)
        .directive("miValidationClass", miValidationClass)
        .directive("miCriteriaString", miCriteriaString)
        .directive("miExpressionBuilder", miExpressionBuilder)

        .controller("ActionEditorCtrl", ActionEditorCtrl)

        .factory("ActionResultModel", ActionResultModel)
        .controller("ActionResultCtrl", ActionResultCtrl)
        .factory("ConditionalModel", ConditionalModel)
        .controller("ConditionalStatementCtrl", ConditionalStatementCtrl)
        .factory("ShowMessageModel", ShowMessageModel)
        .controller("ShowMessageCtrl", ShowMessageCtrl)
        .factory("UpdateControlsModel", UpdateControlsModel)
        .controller("UpdateControlsCtrl", UpdateControlsCtrl)
        .factory("SaveAllModel", SaveAllModel)
        .controller("SaveAllCtrl", SaveAllCtrl)
        .factory("InsertRecordModel", InsertRecordModel)
        .controller("InsertRecordCtrl", InsertRecordCtrl)
        .factory("UpdateRecordModel", UpdateRecordModel)
        .controller("UpdateRecordCtrl", UpdateRecordCtrl)
        .factory("SetActiveRecordModel", SetActiveRecordModel)
        .controller("SetActiveRecordCtl", SetActiveRecordCtl)
        .factory("TextFunctionsModel", TextFunctionsModel)
        .controller("TextFunctionsCtrl", TextFunctionsCtrl)
        .factory("MathFunctionsModel", MathFunctionsModel)
        .controller("MathFunctionsCtrl", MathFunctionsCtrl)
        .factory("ShowHideControlsModel", ShowHideControlsModel)
        .controller("ShowHideControlCtrl", ShowHideControlCtrl)
        .factory("EnableDisableControlsModel", EnableDisableControlsModel)
        .controller("EnableDisableControlCtrl", EnableDisableControlCtrl)
        .factory("SetControlFocusModel", SetControlFocusModel)
        .controller("SetControlFocusCtrl", SetControlFocusCtrl)
        .factory("ClearScreenModel", ClearScreenModel)
        .controller("ClearScreenCtrl", ClearScreenCtrl)
        .factory("GoToScreenModel", GoToScreenModel)
        .controller("GoToScreenCtrl", GoToScreenCtrl)
        .factory("RefreshControlModel", RefreshControlModel)
        .controller("RefreshControlCtrl", RefreshControlCtrl)
        .factory("SetViewFilterModel", SetViewFilterModel)
        .controller("SetViewFilterCtrl", SetViewFilterCtrl)
        .factory("DateFunctionsModel", DateFunctionsModel)
        .controller("DateFunctionsCtrl", DateFunctionsCtrl)
        .factory("SendEmailModel", SendEmailModel)
        .controller("SendEmailCtrl", SendEmailCtrl)
        .factory("CheckPermissionModel", CheckPermissionModel)
        .controller("CheckPermissionCtrl", CheckPermissionCtrl)
        .factory("GenerateReportModel", GenerateReportModel)
        .controller("GenerateReportCtrl", GenerateReportCtrl)
        .factory("DeleteRecordModel", DeleteRecordModel)
        .controller("DeleteRecordCtrl", DeleteRecordCtrl)
        .factory("RetrieveValuesModel", RetrieveValuesModel)
        .controller("RetrieveValuesCtrl", RetrieveValuesCtrl)
        .factory("CreateShortUrlModel", CreateShortUrlModel)
        .controller("CreateShortUrlCtrl", CreateShortUrlCtrl)
        .factory("CallWebServiceModel", CallWebServiceModel)
        .controller("CallWebServiceCtrl", CallWebServiceCtrl)
        .factory("StopProcessingModel", StopProcessingModel)
        .controller("StopProcessingCtrl", StopProcessingCtrl)
        .factory("LoopThroughTableModel", LoopThroughTableModel)
        .controller("LoopThroughTableCtrl", LoopThroughTableCtrl)
        .factory("PrepareAccountingModel", PrepareAccountingModel)
        .controller("PrepareAccountingCtrl", PrepareAccountingCtrl)
        .controller("ProcessPaymentsCtrl", ProcessPaymentsCtrl)
        .factory("ProcessPaymentsModel", ProcessPaymentsModel)
        .controller("ProcessPaymentsV2Ctrl", ProcessPaymentsV2Ctrl)
        .factory("ProcessPaymentsV2Model", ProcessPaymentsV2Model)
        .factory("LoopThroughGridModel", LoopThroughGridModel)
        .controller("LoopThroughGridCtrl", LoopThroughGridCtrl)
        .factory("CallActionSetModel", CallActionSetModel)
        .controller("CallActionSetCtrl", CallActionSetCtrl)
        .factory("SharedResultModel", SharedResultModel)
        .controller("SharedResultCtrl", SharedResultCtrl)
        .factory("GoToWebpageModel", GoToWebpageModel)
        .controller("GoToWebpageCtrl", GoToWebpageCtrl)
        .factory("ExpandCollapseSectionModel", ExpandCollapseSectionModel)
        .controller("ExpandCollapseSectionCtrl", ExpandCollapseSectionCtrl)
        .factory("ShowRightPanelModel", ShowRightPanelModel)
        .controller("ShowRightPanelCtrl", ShowRightPanelCtrl)
        .factory("ValidateControlsModel", ValidateControlsModel)
        .controller("ValidateControlsCtrl", ValidateControlsCtrl)
        .factory("LoopThroughDocumentsModel", LoopThroughDocumentsModel)
        .controller("LoopThroughDocumentsCtrl", LoopThroughDocumentsCtrl)
        .factory("LoopThroughListModel", LoopThroughListModel)
        .controller("LoopThroughListCtrl", LoopThroughListCtrl)
        .factory("AddAttachmentModel", AddAttachmentModel)
        .controller("AddAttachmentCtrl", AddAttachmentCtrl)
        .factory("RetrieveValuesFromEmailModel", RetrieveValuesFromEmailModel)
        .controller("RetrieveValuesFromEmailCtrl", RetrieveValuesFromEmailCtrl)
        .factory("IsReadOnlyModel", IsReadOnlyModel)
        .controller("IsReadOnlyCtrl", IsReadOnlyCtrl)
        .factory("RetrieveExchangeRateModel", RetrieveExchangeRateModel)
        .controller("RetrieveExchangeRateCtrl", RetrieveExchangeRateCtrl)
        .factory("CurrencyConversionModel", CurrencyConversionModel)
        .controller("CurrencyConversionCtrl", CurrencyConversionCtrl)
        .factory("MergeEntitiesModel", MergeEntitiesModel)
        .controller("MergeEntitiesCtrl", MergeEntitiesCtrl)
        .factory("MappingModel", MappingModel)
        .controller("MappingCtrl", MappingCtrl)

        .factory("SendMobilePushNotificationModel", SendMobilePushNotificationModel)
        .controller("SendMobilePushNotificationCtrl", SendMobilePushNotificationCtrl)
        .factory("SendSmsModel", SendSmsModel)
        .controller("SendSmsCtrl", SendSmsCtrl)

        .factory("OpenPopUpModel", OpenPopUpModel)
        .controller("OpenPopUpCtrl", OpenPopUpCtrl)
  
        .factory("ClosePopUpModel", ClosePopUpModel)
        .controller("ClosePopUpCtrl", ClosePopUpCtrl)

        .factory("ShowToastModel", ShowToastModel)
        .controller("ShowToastCtrl", ShowToastCtrl)

        .factory("aeCriteriaBuilderModel", aeCriteriaBuilderModel)
        .factory("aeCriteriaBuilderSvc", aeCriteriaBuilderSvc)

        .directive("miaeCriteriaBuilder", miaeCriteriaBuilder)
        .directive("miaeCriteriaStatement", miaeCriteriaStatement)
        .directive("miaeCriteriaRow", miaeCriteriaRow)
};

export default registrations;
