/* eslint-disable no-console */
import React from 'react';
import InsightCard from '../src/InsightCard';

export default {
  component: InsightCard,
  title: 'm-one/InsightCard',
  argTypes: {
    title: {
      control: 'text',
      description: 'The title text displayed in the card header',
    },
    value: {
      control: 'text',
      description: 'The metric value to display prominently',
    },
    linkText: {
      control: 'text',
      description: 'Text for the action link at the bottom',
    },
    showInfoIcon: {
      control: 'boolean',
      description: 'Whether to show the info icon in the header',
    },
    isLoading: {
      control: 'boolean',
      description: 'Whether to show loading skeleton state',
    },
    infoTooltipContent: {
      control: 'text',
      description: 'Tooltip content shown on hover of info icon',
    },
    onCardClick: { action: 'card clicked' },
  },
  parameters: {
    cssresources: [
      {
        id: 'source-sans-pro',
        code: `<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;600&display=swap" rel="stylesheet">`,
        picked: true,
      },
    ],
  },
};

// Chart icon component for stories
const ChartIcon = () => (
  <svg width='16' height='16' viewBox='0 0 16 16' fill='none'>
    <rect x='2' y='10' width='3' height='4' fill='#545F67' />
    <rect x='6.5' y='6' width='3' height='8' fill='#545F67' />
    <rect x='11' y='2' width='3' height='12' fill='#545F67' />
  </svg>
);

const Template = (args) => <InsightCard {...args} />;

export const Default = Template.bind({});
Default.args = {
  title: 'Revenue distribution',
  value: '60%',
  linkText: 'View customers',
  icon: <ChartIcon />,
  showInfoIcon: true,
};

export const WithoutInfoIcon = Template.bind({});
WithoutInfoIcon.args = {
  title: 'Total Sales',
  value: '$125,000',
  linkText: 'View details',
  icon: <ChartIcon />,
  showInfoIcon: false,
};

export const WithoutIcon = Template.bind({});
WithoutIcon.args = {
  title: 'Active Users',
  value: '1,234',
  linkText: 'View list',
  showInfoIcon: true,
};

export const WithoutLink = Template.bind({});
WithoutLink.args = {
  title: 'Conversion Rate',
  value: '23.5%',
  icon: <ChartIcon />,
  showInfoIcon: false,
};

export const LargeValue = Template.bind({});
LargeValue.args = {
  title: 'Annual Revenue',
  value: '$1,234,567',
  linkText: 'View breakdown',
  icon: <ChartIcon />,
  showInfoIcon: true,
};

export const Minimal = Template.bind({});
Minimal.args = {
  title: 'Metric Name',
  value: '42',
};

export const Loading = Template.bind({});
Loading.args = {
  title: 'My pending estimates',
  value: '',
  icon: <ChartIcon />,
  isLoading: true,
};
Loading.parameters = {
  docs: {
    description: {
      story: 'Loading state with skeleton loaders matching Figma design (node-id: 1512-19854)',
    },
  },
};

export const Clickable = Template.bind({});
Clickable.args = {
  title: 'Revenue distribution',
  value: '60%',
  linkText: 'View customers →',
  icon: <ChartIcon />,
  showInfoIcon: true,
  onCardClick: () => console.log('Card clicked!'),
};
Clickable.parameters = {
  docs: {
    description: {
      story: 'Entire card is clickable with hover effect (node-id: 2023-47632). Hover to see the shadow effect.',
    },
  },
};

export const WithTooltip = Template.bind({});
WithTooltip.args = {
  title: 'Revenue distribution',
  value: '60%',
  linkText: 'View customers',
  icon: <ChartIcon />,
  showInfoIcon: true,
  infoTooltipContent: 'The percentage of your total revenue generated by your top customers.',
};
WithTooltip.parameters = {
  docs: {
    description: {
      story:
        'Card with tooltip on info icon (node-id: 2030-11378). Hover over the info icon to see the tooltip. Tooltip specs: 200px width, #0F1B31 background, #FFF text, 12px Source Sans Pro SemiBold (600), 16px line-height, 4px vertical / 8px horizontal padding, 2px border-radius.',
    },
  },
};

export const WithPositiveDelta = Template.bind({});
WithPositiveDelta.args = {
  title: 'Total spent',
  value: '$24,650',
  delta: { value: '12%', label: 'from last month' },
};
WithPositiveDelta.parameters = {
  docs: {
    description: {
      story:
        'Delta slot with implicit positive direction. `delta.direction` is inferred from the sign of `delta.value` when omitted — here `"12%"` is parsed as +12 → up → green.',
    },
  },
};

export const WithNegativeDelta = Template.bind({});
WithNegativeDelta.args = {
  title: 'Open invoices',
  value: '8',
  delta: { value: -3, label: 'fewer than last week' },
};
WithNegativeDelta.parameters = {
  docs: {
    description: { story: 'Negative delta. Direction inferred from numeric sign.' },
  },
};

export const WithNeutralDelta = Template.bind({});
WithNeutralDelta.args = {
  title: 'Active accounts',
  value: '142',
  delta: { value: '0', label: 'no change' },
};
WithNeutralDelta.parameters = {
  docs: {
    description: { story: 'Zero value → neutral direction → grey color, em-dash glyph.' },
  },
};

export const WithExplicitDirection = Template.bind({});
WithExplicitDirection.args = {
  title: 'Conversion rate',
  value: '23.5%',
  delta: { value: '2.1pp', label: 'vs target', direction: 'up' },
};
WithExplicitDirection.parameters = {
  docs: {
    description: {
      story:
        'Caller can override direction explicitly — useful when `value` is non-numeric (e.g. "2.1pp") or when "up vs target" doesn\'t correlate with sign.',
    },
  },
};
